### PR TITLE
Add docs about es6 to es5 transpiling

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/19)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/board-overview.asciidoc, line 20 at r1](https://reviewable.io:443/reviews/vaadin/board/19#-Kh1goHiyqgWztwwQ1_u:-Kh1goHiyqgWztwwQ1_v:bnieni5) ([raw file](https://github.com/vaadin/board/blob/0f6155629e43b01cc7c84c205664f185d276d295/documentation/board-overview.asciidoc#L20)):*
> ```AsciiDoc
> - Supports nested regions.
> 
> = Known Issues
> ```

Wouldn't put it as known issue

---

*[documentation/board-overview.asciidoc, line 29 at r1](https://reviewable.io:443/reviews/vaadin/board/19#-Kh1ggSroNqR_0KFgzjg:-Kh1ggSsy0GOs6gpoQ92:b-cwfxla) ([raw file](https://github.com/vaadin/board/blob/0f6155629e43b01cc7c84c205664f185d276d295/documentation/board-overview.asciidoc#L29)):*
> ```AsciiDoc
> ----
>   "builds": [{
>     "name": "vbd-es5",
> ```

use generic name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/19)*

**Comment by rogozinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/board-overview.asciidoc, line 20 at r1](https://reviewable.io:443/reviews/vaadin/board/19#-Kh1goHiyqgWztwwQ1_u:-Kh635-5YjAXPo4I94AT:bpdhts1) ([raw file](https://github.com/vaadin/board/blob/0f6155629e43b01cc7c84c205664f185d276d295/documentation/board-overview.asciidoc#L20)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

Wouldn't put it as known issue
</blockquote></details>

Where you want to put it?
In other products we have "Limitations" but this doesn't look like limitations either :)

---

*[documentation/board-overview.asciidoc, line 29 at r1](https://reviewable.io:443/reviews/vaadin/board/19#-Kh1ggSroNqR_0KFgzjg:-Kh63EajSHRweBrn-ZjI:b-896fix) ([raw file](https://github.com/vaadin/board/blob/0f6155629e43b01cc7c84c205664f185d276d295/documentation/board-overview.asciidoc#L29)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

use generic name
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/19)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/board-overview.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/board/19#-Kh64cpV9hU9P2F7Xj1G:-Kh64cpWOJDwcTj0cleD:b-vvvm75) ([raw file](https://github.com/vaadin/board/blob/0f6155629e43b01cc7c84c205664f185d276d295/documentation/board-overview.asciidoc#L22)):*
> ```AsciiDoc
> = Known Issues
> 
> - Vaadin Board is using Polymer 2 and ES6. To support IE11 and Safari you need to transpile ES6 to ES5.
> ```

Which Safari version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/19)*

**Comment by rogozinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/board-overview.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/board/19#-Kh64cpV9hU9P2F7Xj1G:-Kh6DdO93UFH7EHNyRb0:bompoxu) ([raw file](https://github.com/vaadin/board/blob/0f6155629e43b01cc7c84c205664f185d276d295/documentation/board-overview.asciidoc#L22)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Which Safari version?
</blockquote></details>

Version 9, Artur, don't you see it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/19)*

**Comment by rogozinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/board-overview.asciidoc, line 20 at r1](https://reviewable.io:443/reviews/vaadin/board/19#-Kh1goHiyqgWztwwQ1_u:-Kh6DmLgYYiCBdnrz95W:b-896fix) ([raw file](https://github.com/vaadin/board/blob/0f6155629e43b01cc7c84c205664f185d276d295/documentation/board-overview.asciidoc#L20)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Where you want to put it?
In other products we have "Limitations" but this doesn't look like limitations either :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/19)*

**Comment by alvarezguille** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/board-overview.asciidoc, line 35 at r2](https://reviewable.io:443/reviews/vaadin/board/19#-Kh6JE-ZpG5i0Rj7ANwQ:-Kh6JE-_GD79mdHbO2hx:bbqrdjy) ([raw file](https://github.com/vaadin/board/blob/77a0bbe2756de84aed031208fbadc9cf7ea0783d/documentation/board-overview.asciidoc#L35)):*
> ```AsciiDoc
>   }]
> ----
> Running [command]`polymer build` in you application folder will create a traspiled version of your application.
> ```

you -> your

can we mention target folder?

---

*[documentation/board-overview.asciidoc, line 38 at r2](https://reviewable.io:443/reviews/vaadin/board/19#-Kh6JZIEdmQMNM7hSkE3:-Kh6JZIEdmQMNM7hSkE4:b-6vkwr4) ([raw file](https://github.com/vaadin/board/blob/77a0bbe2756de84aed031208fbadc9cf7ea0783d/documentation/board-overview.asciidoc#L38)):*
> = Known Issues

Add empty line before title

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/19)*

**Comment by rogozinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/board-overview.asciidoc, line 35 at r2](https://reviewable.io:443/reviews/vaadin/board/19#-Kh6JE-ZpG5i0Rj7ANwQ:-Kh6VP6oDfiLOv2XP-dr:b-896fix) ([raw file](https://github.com/vaadin/board/blob/77a0bbe2756de84aed031208fbadc9cf7ea0783d/documentation/board-overview.asciidoc#L35)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

you -> your

can we mention target folder?
</blockquote></details>

Done.

---

*[documentation/board-overview.asciidoc, line 38 at r2](https://reviewable.io:443/reviews/vaadin/board/19#-Kh6JZIEdmQMNM7hSkE3:-Kh6VPQjY33fs_5haOUv:b-896fix) ([raw file](https://github.com/vaadin/board/blob/77a0bbe2756de84aed031208fbadc9cf7ea0783d/documentation/board-overview.asciidoc#L38)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> = Known Issues

Add empty line before title
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/19)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/19)*

**Pull request merged**
