### PR TITLE
[DASH-97] - Implement support for columns API

### PR DESCRIPTION
**Pull request by svenruppert**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/50)

### CODE REVIEW

**Comment by rogozinds** [comment]
Reviewed 12 of 14 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 4 at r2](https://reviewable.io:443/reviews/vaadin/board/50#-KkEi71G3RRduLkZq4ol:-KkEi71G3RRduLkZq4om:bpcydc8) ([raw file](https://github.com/vaadin/board/blob/43378083acf0eb88b61684642cc7b19b0e4927d8/addon/src/main/java/com/vaadin/board/Board.java#L4)):*
> import java.util.Collection;
Remove from patch, as the only change

---

*[addon/src/main/java/com/vaadin/board/Row.java, line 78 at r2](https://reviewable.io:443/reviews/vaadin/board/50#-KkEiDY2feKQLpfGB9Vp:-KkEiDY2feKQLpfGB9Vq:b-dy3byv) ([raw file](https://github.com/vaadin/board/blob/43378083acf0eb88b61684642cc7b19b0e4927d8/addon/src/main/java/com/vaadin/board/Row.java#L78)):*
>         //        super.addComponents(components); //Quest - not sure if this is really the same
Let's leave this as it was. super.addComponents should handle everything.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/ColsUI.java, line 18 at r2](https://reviewable.io:443/reviews/vaadin/board/50#-KkEiiromPJj_yHuebMY:-KkEiiromPJj_yHuebMZ:bulii8u) ([raw file](https://github.com/vaadin/board/blob/43378083acf0eb88b61684642cc7b19b0e4927d8/integration-tests/src/main/java/com/vaadin/addon/board/testUI/ColsUI.java#L18)):*
> //                board.setWidth(1024, Unit.PIXELS);
Remove commented code. Or uncomment it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/50)*

**Comment by svenruppert** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 4 at r2](https://reviewable.io:443/reviews/vaadin/board/50#-KkEi71G3RRduLkZq4ol:-KkF12tCGFxZpIZMNuk0:b-896fix) ([raw file](https://github.com/vaadin/board/blob/43378083acf0eb88b61684642cc7b19b0e4927d8/addon/src/main/java/com/vaadin/board/Board.java#L4)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> import java.util.Collection;
Remove from patch, as the only change
</blockquote></details>

Done.

---

*[addon/src/main/java/com/vaadin/board/Row.java, line 78 at r2](https://reviewable.io:443/reviews/vaadin/board/50#-KkEiDY2feKQLpfGB9Vp:-KkF1MNUvqeLgxdBGGb0:b-9f4v1j) ([raw file](https://github.com/vaadin/board/blob/43378083acf0eb88b61684642cc7b19b0e4927d8/addon/src/main/java/com/vaadin/board/Row.java#L78)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>         //        super.addComponents(components); //Quest - not sure if this is really the same
Let's leave this as it was. super.addComponents should handle everything.
</blockquote></details>

well, but this is not setting the cols value 1 for every added component. But I will remove it.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/ColsUI.java, line 18 at r2](https://reviewable.io:443/reviews/vaadin/board/50#-KkEiiromPJj_yHuebMY:-KkF1fG1F4k6Sbpvsi5j:b-896fix) ([raw file](https://github.com/vaadin/board/blob/43378083acf0eb88b61684642cc7b19b0e4927d8/integration-tests/src/main/java/com/vaadin/addon/board/testUI/ColsUI.java#L18)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> //                board.setWidth(1024, Unit.PIXELS);
Remove commented code. Or uncomment it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/50)*

**Comment by svenruppert** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Row.java, line 78 at r2](https://reviewable.io:443/reviews/vaadin/board/50#-KkEiDY2feKQLpfGB9Vp:-KkF42tbwamheZo1wOAV:b-896fix) ([raw file](https://github.com/vaadin/board/blob/43378083acf0eb88b61684642cc7b19b0e4927d8/addon/src/main/java/com/vaadin/board/Row.java#L78)):*
<details><summary><i>Previously, svenruppert (Sven Ruppert) wrote…</i></summary><blockquote>

well, but this is not setting the cols value 1 for every added component. But I will remove it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/50)*

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/50#-:-KkFJHd2CyqQGFHrx38k:bnfp4nl)*

**Pull request merged**
