### PR TITLE
Add declarative support

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/64)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 86 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrr-xYATqOW3OpfxUd:-Klrr-xYATqOW3OpfxUe:b-hq7h2t) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/Board.java#L86)):*
> ```Java
>         row.setParent(this);
>       } else {
>         throw new DesignException("Board can have only Row as a child component.");
> ```

should `Row` be `<vaadin-board-row>` or whatever you have in the declarative file?

---

*[addon/src/main/java/com/vaadin/board/Row.java, line 180 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrs0h7muv-q_kz6Si7:-Klrs0h7muv-q_kz6Si8:bdjbkw4) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/Row.java#L180)):*
> ```Java
>             int cols = 1;
>             for (Attribute attr : childComponent.attributes()) {
>                 if (attr.getKey().equals("board-cols")) {
> ```

Shouldn't this be `:board-cols` to be compatible with the spec that says unprefixed attributes belong to the element they are added to and a ":" prefix indicates they belong to the parent. That also makes the custom `board-` prefix unnecessary so it can be just `:cols`

---

*[addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrrl372py4ShzK_SWP:-Klrrl372py4ShzK_SWQ:b-lfkna7) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java#L10)):*
> ```Java
> import sun.reflect.generics.reflectiveObjects.NotImplementedException;
> 
> public class BoardComponentMapper extends Design.DefaultComponentMapper {
> ```

What is this class for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/64)*

**Comment by Artur-** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Row.java, line 195 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-KlrsSsKrV5G3bAYgSCX:-KlrsSsLqLJRbTT1qfCw:bty8e50) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/Row.java#L195)):*
> ```Java
>             Component comp = it.next();
>             Element childElement = designContext.createElement(comp);
>             int boarCols = getCols(comp);
> ```

boardCols

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/64)*

**Comment by rogozinds** [comment]
Reviewed 2 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 86 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrr-xYATqOW3OpfxUd:-KlsFkO-NTx24tr2mZTI:b-896fix) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/Board.java#L86)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

should `Row` be `<vaadin-board-row>` or whatever you have in the declarative file?
</blockquote></details>

Done.

---

*[addon/src/main/java/com/vaadin/board/Row.java, line 180 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrs0h7muv-q_kz6Si7:-KlsG6SGlcqwJC3AGmqp:b-2hsdnl) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/Row.java#L180)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Shouldn't this be `:board-cols` to be compatible with the spec that says unprefixed attributes belong to the element they are added to and a ":" prefix indicates they belong to the parent. That also makes the custom `board-` prefix unnecessary so it can be just `:cols`
</blockquote></details>

I think current one makes things just more clear. The issue is that children component can have different board-cols value.
For example:
it will be 

---

*[addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrrl372py4ShzK_SWP:-KlsEcsss0AJDx9rdkzZ:bb0bmam) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java#L10)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

What is this class for?
</blockquote></details>

That's  acustom component mapper, we need it because the default Component mapper is used only for Vaadin Components,
that are  in com.vaadin.ui package. So if not using CustomComponent mapper, default one will try to initiate the
com.vaadin.ui.Board class?
Instead of com.vaadin.board.Board.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/64)*

**Comment by rogozinds** [comment]
Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Row.java, line 195 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-KlrsSsKrV5G3bAYgSCX:-KlsIPW28LI8mpgkcqbV:b-896fix) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/Row.java#L195)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

boardCols
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/64)*

**Comment by Artur-** [comment]
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Row.java, line 180 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrs0h7muv-q_kz6Si7:-KlsIrm_6ZOvxFCRf3-D:b-a2vume) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/Row.java#L180)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

I think current one makes things just more clear. The issue is that children component can have different board-cols value.
For example:
it will be 
</blockquote></details>

Ok, but the spec says it's wrong

---

*[addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrrl372py4ShzK_SWP:-KlsJ2dCJ-M1_84fqbYZ:b1dbnd1) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java#L10)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

That's  acustom component mapper, we need it because the default Component mapper is used only for Vaadin Components,
that are  in com.vaadin.ui package. So if not using CustomComponent mapper, default one will try to initiate the
com.vaadin.ui.Board class?
Instead of com.vaadin.board.Board.
</blockquote></details>

It's not used anywhere? Also the API is static so you can't really use it from an add-on, it's only for the application developer. The declarative is explicitly that `vaadin-` maps to `com.vaadin.ui`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/64)*

**Comment by rogozinds** [comment]
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Row.java, line 180 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrs0h7muv-q_kz6Si7:-KlsNiDxYm7z7RpYdwEv:b-886gsx) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/Row.java#L180)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Ok, but the spec says it's wrong
</blockquote></details>

Fixed

---

*[addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrrl372py4ShzK_SWP:-KlsNwLJCfoudGPRF7q_:b9cmy6l) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java#L10)):*
> anywhere
It's used in tests. And in testUI. This is how it's done for charts. You need to set the mapper first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/64)*

**Comment by rogozinds** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrrl372py4ShzK_SWP:-KlsdDj0gitTdhH8lEYq:b-rfzeut) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java#L10)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> anywhere
It's used in tests. And in testUI. This is how it's done for charts. You need to set the mapper first.
</blockquote></details>

Removed Custom mapper ,changed tests to use package-mapping

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/64)*

**Comment by rogozinds** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/board/64#-Klrrl372py4ShzK_SWP:-KlsdLH0RhQborZaxAIR:b-896fix) ([raw file](https://github.com/vaadin/board/blob/fb928f9811356c56b0b3c51c7aa7c56ace701c9c/addon/src/main/java/com/vaadin/board/declarative/BoardComponentMapper.java#L10)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Removed Custom mapper ,changed tests to use package-mapping
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/64)*

**Comment by DiegoCardoso** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/64#-:-Klw18SL4VJs6sz0QU3k:bnfp4nl)*

**Comment by Artur-** [comment]
Reviewed 1 of 8 files at r1, 1 of 2 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/src/test/java/com/vaadin/board/declarative/BoardWriterTest.java, line 19 at r3](https://reviewable.io:443/reviews/vaadin/board/64#-Klw2HOybeC6k_rZmKah:-Klw2HOz1aPm_m4vDSPP:b-jhvhwy) ([raw file](https://github.com/vaadin/board/blob/ec48c597101a3bd969b8e315ed98e42691147780/addon/src/test/java/com/vaadin/board/declarative/BoardWriterTest.java#L19)):*
> ```Java
> 
>     private static final String BOARD_WITH_ONE_ROW_CONFIG=
>         "<vaadin-board size-full> \n" +
> ```

vaadin-board?

---

*[addon/src/test/java/com/vaadin/board/declarative/BoardWriterTest.java, line 114 at r3](https://reviewable.io:443/reviews/vaadin/board/64#-Klw2OjvXhle3M4cY6lQ:-Klw2OjvXhle3M4cY6lR:b-6isjfn) ([raw file](https://github.com/vaadin/board/blob/ec48c597101a3bd969b8e315ed98e42691147780/addon/src/test/java/com/vaadin/board/declarative/BoardWriterTest.java#L114)):*
> ```Java
>             String doc = outputStream.toString("UTF-8");
> 
>             doc = doc.replace("com_vaadin_board-board","vaadin-board");
> ```

This looks like a confusing hack. Why not add package mapping in the declarative?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/64)*

**Pull request merged**
