### PR TITLE
Add removeRow method to board.

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/42)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-Kjc9ROHKhIxBnRIciMA:-Kjc9ROHKhIxBnRIciMB:b-n64qh8) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/addon/src/main/java/com/vaadin/board/Board.java#L57)):*
> ```Java
> 
>     /**
>      * Removes a row from the board.
> ```

nit: could be `the given row`

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-Kjc9ZBu9VwHezddn3l5:-Kjc9ZBu9VwHezddn3l6:bjhj7mf) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/addon/src/main/java/com/vaadin/board/Board.java#L59)):*
> ```Java
>      * Removes a row from the board.
>      *
>      * All the added components have cols set to 1, i.e. use one slot in the
> ```

What does this mean? Copy paste error?

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 65 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcEguQ3WFq1rn1lR6G:-KjcEguQ3WFq1rn1lR6H:b-n64l4n) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/addon/src/main/java/com/vaadin/board/Board.java#L65)):*
> ```Java
>      **/
>     public void removeRow(Row row) {
>         for (Row r : rows) {
> ```

Why not rows.remove(row)? 

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/RemoveComponentUI.java, line 8 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcEx84BF51YAlZxMvb:-KjcEx84BF51YAlZxMvc:bemc4sm) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/integration-tests/src/main/java/com/vaadin/addon/board/testUI/RemoveComponentUI.java#L8)):*
> ```Java
> import com.vaadin.ui.Button;
> 
> public class RemoveComponentUI extends AbstractTestUI {
> ```

This looks like it could be a unit test instead.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/RowRemoveUI.java, line 9 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcFLGKEQ7YXglCegUd:-KjcFLGKEQ7YXglCegUe:b-wbaek1) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/integration-tests/src/main/java/com/vaadin/addon/board/testUI/RowRemoveUI.java#L9)):*
> ```Java
> import com.vaadin.ui.VerticalLayout;
> 
> public class RowRemoveUI extends AbstractTestUI {
> ```

If you make a little more generic UI, you can test a lot of things with only one UI. 
E.g. add buttons inside the board to remove the row where the button is, add a button for inserting a row at index 1, 2 or 3

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java, line 20 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcFbYmAjkFoBSweqhr:-KjcFbYmAjkFoBSweqhs:b-rhlkug) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java#L20)):*
> ```Java
>     @Test
>     public void basicLayout_boardTabletSize_twoRowsAndTwoItemsInRow() {
>         WebElement board = getDriver().findElement(By.tagName("vaadin-board"));
> ```

`$(BoardElement.class).first()` if you just add the class with the mapping

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcFjqIVEdH2WHA9R5a:-KjcFjqIVEdH2WHA9R5b:byh36zc) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java#L26)):*
> ```Java
>         ButtonElement btn4 = $(ButtonElement.class).caption("Button 4").first();
> 
>         Assert.assertEquals("Btn1 should have Y == 0", board.getLocation().getY(), btn1.getLocation().getY());
> ```

This does not check that y==0, it checks that board.y == row.y

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/RemoveComponentIT.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcFpdF3GKmEG15Bhv-:-KjcFpdF3GKmEG15Bhv0:b-isby6u) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/RemoveComponentIT.java#L24)):*
> ```Java
>         ButtonElement btn2 = $(ButtonElement.class).caption("Button 3").first();
> 
>         Assert.assertEquals("Btn1 should have Y == 0" , board.getLocation().getY(), btn1.getLocation().getY());
> ```

This does not check that y==0, it checks that board.y == button.y

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Comment by rogozinds** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-Kjc9ROHKhIxBnRIciMA:-KjcGpgMPsTumE4MkjnT:b-896fix) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/addon/src/main/java/com/vaadin/board/Board.java#L57)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

nit: could be `the given row`
</blockquote></details>

Done.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-Kjc9ZBu9VwHezddn3l5:-KjcGrtrxMXNGPEHXet9:b-896fix) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/addon/src/main/java/com/vaadin/board/Board.java#L59)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

What does this mean? Copy paste error?
</blockquote></details>

Done.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 65 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcEguQ3WFq1rn1lR6G:-KjcH4MY-_Aj9DS5tuuK:b-896fix) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/addon/src/main/java/com/vaadin/board/Board.java#L65)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why not rows.remove(row)? 
</blockquote></details>

Done.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/RemoveComponentUI.java, line 8 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcEx84BF51YAlZxMvb:-Kjg0pxhuLGMv_1YK2Cs:b8alfs8) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/integration-tests/src/main/java/com/vaadin/addon/board/testUI/RemoveComponentUI.java#L8)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This looks like it could be a unit test instead.
</blockquote></details>

We want to test inside vaadin application, how it can be Unit test?

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/RowRemoveUI.java, line 9 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcFLGKEQ7YXglCegUd:-Kjg1F6CichBJwMMUC1r:b-g1op45) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/integration-tests/src/main/java/com/vaadin/addon/board/testUI/RowRemoveUI.java#L9)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

If you make a little more generic UI, you can test a lot of things with only one UI. 
E.g. add buttons inside the board to remove the row where the button is, add a button for inserting a row at index 1, 2 or 3
</blockquote></details>

I don't need it right now, I'm removing  one row? If later we need some generic UI we can create it, I don't see a point to spend time on creating test UI "in advance".

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/RemoveComponentIT.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcFpdF3GKmEG15Bhv-:-KjcIJ6p-MWGgHP4_4l-:bnu4eeb) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/RemoveComponentIT.java#L24)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This does not check that y==0, it checks that board.y == button.y
</blockquote></details>

Done. Now it's checking for children size.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java, line 20 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcFbYmAjkFoBSweqhr:-KjcIB8urn1JHJAhmnhC:b-gsmv4q) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java#L20)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

`$(BoardElement.class).first()` if you just add the class with the mapping
</blockquote></details>

That would be a separate patch.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/board/42#-KjcFjqIVEdH2WHA9R5a:-KjcIFkHe-R_XX0POaIT:bb6un1j) ([raw file](https://github.com/vaadin/board/blob/19cc0835579f8c9b2c12e53502b4a2c110ed6d17/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java#L26)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This does not check that y==0, it checks that board.y == row.y
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Comment by alvarezguille** [comment]
*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java, line 33 at r2](https://reviewable.io:443/reviews/vaadin/board/42#-Kjg7ldQ1oXQiuq4ljaz:-Kjg7ldQ1oXQiuq4ljb-:b-anj747) ([raw file](https://github.com/vaadin/board/blob/e48a5b8ad78b59958065d747b8859c9e9a4356c6/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java#L33)):*
>         Assert.assertEquals("Btn3 should have Y == btn1.height", btn1.getSize().getHeight(), btn3.getLocation().getY());
>         Assert.assertEquals("Btn3 should have Y == btn1.height", btn2.getSize().getHeight(), btn4.getLocation().getY());

do these still work after the margin?
sorry I didn't catch it before

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Comment by alvarezguille** [comment]
*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java, line 33 at r2](https://reviewable.io:443/reviews/vaadin/board/42#-Kjg7ldQ1oXQiuq4ljaz:-Kjg9McnRvqCMwXzmEGZ:b-ina9eg) ([raw file](https://github.com/vaadin/board/blob/e48a5b8ad78b59958065d747b8859c9e9a4356c6/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java#L33)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>         Assert.assertEquals("Btn3 should have Y == btn1.height", btn1.getSize().getHeight(), btn3.getLocation().getY());
>         Assert.assertEquals("Btn3 should have Y == btn1.height", btn2.getSize().getHeight(), btn4.getLocation().getY());

do these still work after the margin?
sorry I didn't catch it before
</blockquote></details>

changing to something like `board.getLocation().getY() + btn1.getSize().getHeight(), btn3.getLocation().getY()` seems to work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Comment by rogozinds** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java, line 33 at r2](https://reviewable.io:443/reviews/vaadin/board/42#-Kjg7ldQ1oXQiuq4ljaz:-KjgByhliCDVYDrkVnYo:b-896fix) ([raw file](https://github.com/vaadin/board/blob/e48a5b8ad78b59958065d747b8859c9e9a4356c6/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/BasicIT.java#L33)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

changing to something like `board.getLocation().getY() + btn1.getSize().getHeight(), btn3.getLocation().getY()` seems to work
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Comment by alvarezguille** [comment]
Reviewed 3 of 6 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Comment by Artur-** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 63 at r4](https://reviewable.io:443/reviews/vaadin/board/42#-KjgKVuJ5LqrXUj0KLl0:-KjgKVuKbwD0quHsRWa_:b6y5aij) ([raw file](https://github.com/vaadin/board/blob/5cb5e2ee46554d651a4f310114d7a28f62271882/addon/src/main/java/com/vaadin/board/Board.java#L63)):*
> ```Java
>      **/
>     public void removeRow(Row row) {
>         row.setParent(null);
> ```

Should check that the row is actually in this board to avoid acidentally removing it from another board, e.g.
```
if (rows.remove(row)) {
   ...
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Comment by rogozinds** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 63 at r4](https://reviewable.io:443/reviews/vaadin/board/42#-KjgKVuJ5LqrXUj0KLl0:-KjgXawc7o3carWqulWj:b-8n327p) ([raw file](https://github.com/vaadin/board/blob/5cb5e2ee46554d651a4f310114d7a28f62271882/addon/src/main/java/com/vaadin/board/Board.java#L63)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Should check that the row is actually in this board to avoid acidentally removing it from another board, e.g.
```
if (rows.remove(row)) {
   ...
}
```
</blockquote></details>

Yes, good point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Comment by rogozinds** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 63 at r4](https://reviewable.io:443/reviews/vaadin/board/42#-KjgKVuJ5LqrXUj0KLl0:-Kjg_N7Ze6ww96aFklf1:b-896fix) ([raw file](https://github.com/vaadin/board/blob/5cb5e2ee46554d651a4f310114d7a28f62271882/addon/src/main/java/com/vaadin/board/Board.java#L63)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Yes, good point.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 63 at r4](https://reviewable.io:443/reviews/vaadin/board/42#-KjgKVuJ5LqrXUj0KLl0:-Kjgcj7gbJ_s0-Mup7x8:b-lk3qxi) ([raw file](https://github.com/vaadin/board/blob/5cb5e2ee46554d651a4f310114d7a28f62271882/addon/src/main/java/com/vaadin/board/Board.java#L63)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why the extra contains(row)? remove(row) returns the same thing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Comment by rogozinds** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/42)*

**Pull request merged**
