### PR TITLE
Fix resize at runtime for board

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/55)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/src/main/java/com/vaadin/board/client/BoardConnector.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/board/55#-KkQX6pnxMkpZVOF7w8j:-KkQX6poVNgSJLqsH0vy:b-rj0hm6) ([raw file](https://github.com/vaadin/board/blob/abfb60015bb307c7902c8b2fdfdf58147319f331/addon/src/main/java/com/vaadin/board/client/BoardConnector.java#L42)):*
> ```Java
>     public void onStateChanged(StateChangeEvent stateChangeEvent) {
>         super.onStateChanged(stateChangeEvent);
>         getLayoutManager().addElementResizeListener(getWidget().getElement(), e-> {
> ```

Nooooooooooo
This would add a new listener every time some part of the state is changed. Do this in `init()` instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/55)*

**Comment by alvarezguille** [comment]
*[addon/src/main/java/com/vaadin/board/client/BoardWidget.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/board/55#-KkQXQjS1LnpcpOeNpO_:-KkQXQjS1LnpcpOeNpOa:b-og2isa) ([raw file](https://github.com/vaadin/board/blob/abfb60015bb307c7902c8b2fdfdf58147319f331/addon/src/main/java/com/vaadin/board/client/BoardWidget.java#L24)):*
>     public native void redraw(Element elem)/*-{
>         elem.redraw();
>     }-*/;

can it be done without arguments with this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/55)*

**Comment by rogozinds** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/src/main/java/com/vaadin/board/client/BoardConnector.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/board/55#-KkQX6pnxMkpZVOF7w8j:-KkkKY2EMPKYSPAJBWci:b-896fix) ([raw file](https://github.com/vaadin/board/blob/abfb60015bb307c7902c8b2fdfdf58147319f331/addon/src/main/java/com/vaadin/board/client/BoardConnector.java#L42)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Nooooooooooo
This would add a new listener every time some part of the state is changed. Do this in `init()` instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/55)*

**Comment by rogozinds** [comment]
Reviewed 9 of 12 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/55)*

**Pull request merged**
