### PR TITLE
Refactor overview docs

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/38)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Moves know issues and es6 to es5 transpilation docs from overview to WC basic use.
Uses feature list from release notes.

**Comment by rogozinds** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/board-overview.asciidoc, line 19 at r1](https://reviewable.io:443/reviews/vaadin/board/38#-KjN4si97kdY6ID7NAi9:-KjN4si97kdY6ID7NAiA:b-jes2k5) ([raw file](https://github.com/vaadin/board/blob/1d6e7724680fe85652aee35a5a0c7b25235ee3f8/documentation/board-overview.asciidoc#L19)):*
> Not only does is
Does is?
Looks like should be one one of this.

> Not only does is the component itself responsive
The whole phrase sounds like a 100% TV-shop, I would just leave it.

"Each row reacts individually to the space given to it in a responsive way."

---

*[documentation/board-overview.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/board/38#-KjN5a82TU5JUZvxdjpD:-KjN5a83h67fHiPQByX_:bgkolob) ([raw file](https://github.com/vaadin/board/blob/1d6e7724680fe85652aee35a5a0c7b25235ee3f8/documentation/board-overview.asciidoc#L21)):*
> this
This
The whole sentence is freaky complex. I Would change it:

This allows you to place one widget among multiple slots.

---

*[documentation/board-overview.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/board/38#-KjN6GL8EFhqvWty3rc0:-KjN6GL8EFhqvWty3rc1:b-63f0yn) ([raw file](https://github.com/vaadin/board/blob/1d6e7724680fe85652aee35a5a0c7b25235ee3f8/documentation/board-overview.asciidoc#L22)):*
> You can put a new row within another row to build how ever complex layouts that you want
This also sounds like TV-shop. Why do I want to build "Complex" layout? I want to build easy stuff, but just it should look good.
I understand what you are trying to say, but it sounds like we are adding unnecessary complexity
I would change it to:
You can put one row within another to create different layouts and position you widgets how ever you want. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/38)*

**Comment by rogozinds** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/board-overview.asciidoc, line 21 at r2](https://reviewable.io:443/reviews/vaadin/board/38#-KjNGSdqXF5A55CP3Zel:-KjNGSdqXF5A55CP3Zem:ba9ktl5) ([raw file](https://github.com/vaadin/board/blob/0e679b8c1abbbfad63ffd822dcabd3ce216ae0b1/documentation/board-overview.asciidoc#L21)):*
> . or 25-50-25. or 33-67.·
Should it be commas? Or capital letter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/38)*

**Comment by alvarezguille** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/board-overview.asciidoc, line 21 at r2](https://reviewable.io:443/reviews/vaadin/board/38#-KjNGSdqXF5A55CP3Zel:-KjNHghj5yqNo9qGynts:b-896fix) ([raw file](https://github.com/vaadin/board/blob/0e679b8c1abbbfad63ffd822dcabd3ce216ae0b1/documentation/board-overview.asciidoc#L21)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> . or 25-50-25. or 33-67.·
Should it be commas? Or capital letter?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/38)*

**Comment by rogozinds** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/38)*

**Comment by rogozinds** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/38#-:-Kjam4spRBTP0eQi48UB:bnfp4nl)*

**Pull request merged**
