### PR TITLE
small typing

### PR DESCRIPTION
**Pull request by svenruppert**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/28)

### CODE REVIEW

**Comment by rogozinds** [comment]
Reviewed 1 of 2 files at r1, 2 of 3 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/src/test/java/junit/com/vaadin/board/BoardTest.java, line 14 at r2](https://reviewable.io:443/reviews/vaadin/board/28#-KiAoi2HBRMCacrAUt7L:-KiAoi2I8bpc81Qnf-Bg:bqvqar0) ([raw file](https://github.com/vaadin/board/blob/a438ee496ea0798d998b0dfdd5dfed481e689430/addon/src/test/java/junit/com/vaadin/board/BoardTest.java#L14)):*
> test001()
change it to boardConfiguration_addFiveComponentsToRow_raiseException

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/28)*

**Comment by rogozinds** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/28)*

**Comment by svenruppert** [comment]
Review status: 0 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/src/test/java/junit/com/vaadin/board/BoardTest.java, line 14 at r2](https://reviewable.io:443/reviews/vaadin/board/28#-KiAoi2HBRMCacrAUt7L:-KiiOLAeH7mqx2cIyts2:b-896fix) ([raw file](https://github.com/vaadin/board/blob/a438ee496ea0798d998b0dfdd5dfed481e689430/addon/src/test/java/junit/com/vaadin/board/BoardTest.java#L14)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> test001()
change it to boardConfiguration_addFiveComponentsToRow_raiseException
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/28)*

**Comment by alvarezguille** [comment]
Didn't check in detail, but have some general comments about the PR:
* Don't add "Created by ..." comments on new classes
* Don't push commented code
* Remove .iml file from PR
* Why was addon/src/main/java/com/vaadin/board/BoardWidgetSet.gwt.xml removed?

**Comment by svenruppert** [comment]
not needed anymore

**Pull request closed without merging**
