### PR TITLE
Updated dependency version numbers in documentation

### PR DESCRIPTION
**Pull request by johannesh2**
- Updated dependency version numbers from FW alpha to beta in documentation
- Updated dependency version numbers from Board alpha2 to alpha5 in documentation
- Removed frontend plugin mentions from docs
- Fixed archetype generate command to work with pre-releases

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/72)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[documentation/java-api/installing.asciidoc, line 34 at r1](https://reviewable.io:443/reviews/vaadin/board/72#-KmbBiYaqv8nVxRZUdlA:-KmbBiYaqv8nVxRZUdlB:b-8ho19b) ([raw file](https://github.com/vaadin/board/blob/d24d3b9c2d76f8e68791f0993b4f321bec98e216/documentation/java-api/installing.asciidoc#L34)):*
> &lt;dependency&gt;
>     &lt;groupId&gt;com.vaadin&lt;/groupId&gt;
>     &lt;artifactId&gt;vaadin-board&lt;/artifactId&gt;
>     &lt;version&gt;[replaceable]##1.0.0-alpha5##&lt;/version&gt;
> &lt;/dependency&gt;

should this mention vaadin-board-precompiled too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/72)*

**Comment by johannesh2** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/java-api/installing.asciidoc, line 34 at r1](https://reviewable.io:443/reviews/vaadin/board/72#-KmbBiYaqv8nVxRZUdlA:-KmbEHJvHl4TO4TKeMqb:bt2vr1b) ([raw file](https://github.com/vaadin/board/blob/d24d3b9c2d76f8e68791f0993b4f321bec98e216/documentation/java-api/installing.asciidoc#L34)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> &lt;dependency&gt;
>     &lt;groupId&gt;com.vaadin&lt;/groupId&gt;
>     &lt;artifactId&gt;vaadin-board&lt;/artifactId&gt;
>     &lt;version&gt;[replaceable]##1.0.0-alpha5##&lt;/version&gt;
> &lt;/dependency&gt;

should this mention vaadin-board-precompiled too?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/72)*

**Comment by johannesh2** [comment]
I updated from alpha5 to alpha10. Could someone review this @rogozinds  ?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/72#-:-Kni279UFO99J_-SdAzX:by5nqs1)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/72)*

**Pull request merged**
