### PR TITLE
Add known issue about safari 10

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/22)

### CODE REVIEW

**Comment by rogozinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/board-overview.asciidoc, line 59 at r1](https://reviewable.io:443/reviews/vaadin/board/22#-KhLxO2WkMw3BNhkUjJO:-KhLxO2WkMw3BNhkUjJP:b1adko2) ([raw file](https://github.com/vaadin/board/blob/66f694b35c39fe606fb30cc2a34feacfee93e4ce/documentation/board-overview.asciidoc#L59)):*
> HTML Imports polyfill has a known issue with Safari 10, see details link:https://github.com/Polymer/polymer/issues/4476[here].
Can we add also one sentence what does this mean on practice for an actual user/developer?
For example:
"In practice this means, that Web components will not be loaded correctly."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/22)*

**Comment by rogozinds** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/22)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/board-overview.asciidoc, line 59 at r1](https://reviewable.io:443/reviews/vaadin/board/22#-KhLxO2WkMw3BNhkUjJO:-KhM3FAUW1lWPpHGbb24:b-896fix) ([raw file](https://github.com/vaadin/board/blob/66f694b35c39fe606fb30cc2a34feacfee93e4ce/documentation/board-overview.asciidoc#L59)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> HTML Imports polyfill has a known issue with Safari 10, see details link:https://github.com/Polymer/polymer/issues/4476[here].
Can we add also one sentence what does this mean on practice for an actual user/developer?
For example:
"In practice this means, that Web components will not be loaded correctly."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/22)*

**Comment by rogozinds** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/22#-:-KhM3MZK8YilxVkMppSf:bnfp4nl)*

**Pull request merged**
