### PR TITLE
Create a jar containing all needed HTML+JS

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/62)

### CODE REVIEW

**Comment by rogozinds** [comment]
Reviewed 2 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[precompiled/src/main/frontend/bower.json, line 18 at r1](https://reviewable.io:443/reviews/vaadin/board/62#-Klrs7acquBcQVxKbGDJ:-Klrs7adsWObB4_VnCnC:b67piw4) ([raw file](https://github.com/vaadin/board/blob/83fb8d9c8793eeabf93ac9f4dbf132cf2b1140c9/precompiled/src/main/frontend/bower.json#L18)):*
> ```JSON
>     "webcomponentsjs": "v1.0.0-rc.11"
>   }
> }
> ```

This file is generated so should this file be removed (added to .gitignore)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/62)*

**Comment by Artur-** [comment]
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[precompiled/src/main/frontend/bower.json, line 18 at r1](https://reviewable.io:443/reviews/vaadin/board/62#-Klrs7acquBcQVxKbGDJ:-KlrtjZWwQ8Dk86Gap7W:brbb78h) ([raw file](https://github.com/vaadin/board/blob/83fb8d9c8793eeabf93ac9f4dbf132cf2b1140c9/precompiled/src/main/frontend/bower.json#L18)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

This file is generated so should this file be removed (added to .gitignore)
</blockquote></details>

The frontend plugin uses `bower.json` to detect if the files in the folder have been created, so if I remove it, the other files (which are slightly modified) will be overwritten

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/62)*

**Comment by rogozinds** [comment]
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[precompiled/src/main/frontend/bower.json, line 18 at r1](https://reviewable.io:443/reviews/vaadin/board/62#-Klrs7acquBcQVxKbGDJ:-Kls3k8LuZmKpYOrSXTw:b1t2wsx) ([raw file](https://github.com/vaadin/board/blob/83fb8d9c8793eeabf93ac9f4dbf132cf2b1140c9/precompiled/src/main/frontend/bower.json#L18)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

The frontend plugin uses `bower.json` to detect if the files in the folder have been created, so if I remove it, the other files (which are slightly modified) will be overwritten
</blockquote></details>

Ok. Seems like we can remove frontend plugin and vaadin-frontend-maven-plugin from integration-test pom? Otherwise our test UI still uses it's own plugin but not the precompiled version.
I've done that, and I get an exception
SEVERE: Could not find UI board/HEARTBEAT/
java.lang.ClassNotFoundException: com.vaadin.addon.board.testUI.board/HEARTBEAT/
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.vaadin.addon.board.testUI.TestUIProvider.getUIClass(TestUIProvider.java:29)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/62)*

**Comment by rogozinds** [comment]
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[precompiled/src/main/frontend/bower.json, line 18 at r1](https://reviewable.io:443/reviews/vaadin/board/62#-Klrs7acquBcQVxKbGDJ:-KlsE5iV0tPw3KrOBTc0:b8lj6k0) ([raw file](https://github.com/vaadin/board/blob/83fb8d9c8793eeabf93ac9f4dbf132cf2b1140c9/precompiled/src/main/frontend/bower.json#L18)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Ok. Seems like we can remove frontend plugin and vaadin-frontend-maven-plugin from integration-test pom? Otherwise our test UI still uses it's own plugin but not the precompiled version.
I've done that, and I get an exception
SEVERE: Could not find UI board/HEARTBEAT/
java.lang.ClassNotFoundException: com.vaadin.addon.board.testUI.board/HEARTBEAT/
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.vaadin.addon.board.testUI.TestUIProvider.getUIClass(TestUIProvider.java:29)
</blockquote></details>

after removing frontend plugin from integration-tests, I've also tried to build WAR, and run it on tomcat, it failed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/62)*

**Comment by Artur-** [comment]
Review status: 2 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[precompiled/src/main/frontend/bower.json, line 18 at r1](https://reviewable.io:443/reviews/vaadin/board/62#-Klrs7acquBcQVxKbGDJ:-KlsHeq6OnbRv4mTmT5v:b-yxdqhj) ([raw file](https://github.com/vaadin/board/blob/83fb8d9c8793eeabf93ac9f4dbf132cf2b1140c9/precompiled/src/main/frontend/bower.json#L18)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

after removing frontend plugin from integration-tests, I've also tried to build WAR, and run it on tomcat, it failed.
</blockquote></details>

Done, also works on Tomcat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/62)*

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 5 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/62#-:-KlwGaYeQkVWRMjxJv0y:bnfp4nl)*

**Pull request merged**
