### PR TITLE
Add getting started

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/17)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/webcomponents-api/getting-started.asciidoc, line 49 at r1](https://reviewable.io:443/reviews/vaadin/board/17#-KgoHNyCnyktEQbvXoHv:-KgoHNyCnyktEQbvXoHw:b-kssbbj) ([raw file](https://github.com/vaadin/board/blob/4fd60a0b2581c200a6cfbe3b351344d15a2bd232/documentation/webcomponents-api/getting-started.asciidoc#L49)):*
> [elementname]`html`

what's expected from this?
I think it should either be [elementname]#html# or `html`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/17)*

**Comment by rogozinds** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/webcomponents-api/getting-started.asciidoc, line 49 at r1](https://reviewable.io:443/reviews/vaadin/board/17#-KgoHNyCnyktEQbvXoHv:-Kgs-9Sx3KqhGXbcgnC-:b-vg4cv) ([raw file](https://github.com/vaadin/board/blob/4fd60a0b2581c200a6cfbe3b351344d15a2bd232/documentation/webcomponents-api/getting-started.asciidoc#L49)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> [elementname]`html`

what's expected from this?
I think it should either be [elementname]#html# or `html`
</blockquote></details>

That was made by mistake, here it means just HTML element not a tag changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/17)*

**Comment by rogozinds** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/webcomponents-api/getting-started.asciidoc, line 49 at r1](https://reviewable.io:443/reviews/vaadin/board/17#-KgoHNyCnyktEQbvXoHv:-KgsVj_vFdXcknIzznXw:b-896fix) ([raw file](https://github.com/vaadin/board/blob/4fd60a0b2581c200a6cfbe3b351344d15a2bd232/documentation/webcomponents-api/getting-started.asciidoc#L49)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

That was made by mistake, here it means just HTML element not a tag changed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/17)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/17)*

**Pull request merged**
