### PR TITLE
Feature/dash 27

### PR DESCRIPTION
**Pull request by svenruppert**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/56)

### CODE REVIEW

**Comment by rogozinds** [comment]
Review status: 0 of 24 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[addon/src/main/java/com/vaadin/board/Row.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/board/56#-Kl3O8jU0DPHEwytLlGS:-Kl3O8jU0DPHEwytLlGT:bj9bnkc) ([raw file](https://github.com/vaadin/board/blob/a879e5a0f840940d87db81a4f861cda324b87487/addon/src/main/java/com/vaadin/board/Row.java#L61)):*
>         for (Component component : components) {
>             addComponent(component);
>         }
we don't need it. Parent class will handle it

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/board/56#-Kl3PCzQz88yxE73_2Cd:-Kl3PCzR6pLhoT5X-fM1:bu3emby) ([raw file](https://github.com/vaadin/board/blob/a879e5a0f840940d87db81a4f861cda324b87487/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java#L29)):*
> //@RunOnHub("tb3-hub.intra.itmill.com")
> @RunLocally(value = Browser.CHROME)
Use RunOnHub

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/56)*

**Comment by svenruppert** [comment]
Review status: 0 of 45 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/board/56#-Kl3PCzQz88yxE73_2Cd:-Kl4i1KANtvcchYq4gSY:b-896fix) ([raw file](https://github.com/vaadin/board/blob/a879e5a0f840940d87db81a4f861cda324b87487/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java#L29)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> //@RunOnHub("tb3-hub.intra.itmill.com")
> @RunLocally(value = Browser.CHROME)
Use RunOnHub
</blockquote></details>

Done.

---

*[addon/src/main/java/com/vaadin/board/Row.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/board/56#-Kl3O8jU0DPHEwytLlGS:-Kl4i6VRP_H3npLXL3il:b-896fix) ([raw file](https://github.com/vaadin/board/blob/a879e5a0f840940d87db81a4f861cda324b87487/addon/src/main/java/com/vaadin/board/Row.java#L61)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>         for (Component component : components) {
>             addComponent(component);
>         }
we don't need it. Parent class will handle it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/56)*

**Comment by svenruppert** [comment]
Reviewed 2 of 35 files at r2.
Review status: 2 of 48 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/56)*

**Comment by rogozinds** [comment]
Reviewed 6 of 24 files at r1, 19 of 35 files at r2.
Review status: 27 of 48 files reviewed at latest revision, 6 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 4 at r2](https://reviewable.io:443/reviews/vaadin/board/56#-KlI34i82Fn2Xm612BNO:-KlI34i9GmGl7hreekMw:b9e522b) ([raw file](https://github.com/vaadin/board/blob/9081bf76bd1aabc1b14ea358ad92d9f19f981414/addon/src/main/java/com/vaadin/board/Board.java#L4)):*
> import java.util.Collection;
That's the only change in this file. Remove it.

---

*[integration-tests/config/template_selenium-grids.properties, line 1 at r2](https://reviewable.io:443/reviews/vaadin/board/56#-KlI3S1oBjnfI9Vzgiej:-KlI3S1oBjnfI9Vzgiek:b13bk9d) ([raw file](https://github.com/vaadin/board/blob/9081bf76bd1aabc1b14ea358ad92d9f19f981414/integration-tests/config/template_selenium-grids.properties#L1)):*
> nogrid=locale-ip
> locale-grid=locale-ip
> #vaadin-grid=tb3-hub.intra.itmill.com
What is this file?

---

*[integration-tests/config/template_testbench.properties, line 4 at r2](https://reviewable.io:443/reviews/vaadin/board/56#-KlI3gkaZfrqS489HHs9:-KlI3gkbddiE9MmB0hE8:btcc0ao) ([raw file](https://github.com/vaadin/board/blob/9081bf76bd1aabc1b14ea358ad92d9f19f981414/integration-tests/config/template_testbench.properties#L4)):*
> ```INI
> #firefox.profile.path=path-to/webdriver/gecko/geckodriver
> webdriver.chrome.driver=path-to/webdriver/chrome/chromedriver
> phantomjs.binary.path=path-to/webdriver/phantomjs/phantomjs
> ```

What is this file?

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/Dash27BasicChartUI.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/board/56#-KlI42lgdvEX7vuWsyba:-KlI42lgdvEX7vuWsybb:b1ez9oq) ([raw file](https://github.com/vaadin/board/blob/9081bf76bd1aabc1b14ea358ad92d9f19f981414/integration-tests/src/main/java/com/vaadin/addon/board/testUI/Dash27BasicChartUI.java#L26)):*
> //todo make it dynamic
What does this comment mean? Who will do it and then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/56)*

**Comment by svenruppert** [comment]
Reviewed 14 of 24 files at r1, 31 of 35 files at r2, 4 of 4 files at r3.
Review status: 47 of 48 files reviewed at latest revision, 6 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 4 at r2](https://reviewable.io:443/reviews/vaadin/board/56#-KlI34i82Fn2Xm612BNO:-KlI6S1lzqFPkirXIqz0:b-896fix) ([raw file](https://github.com/vaadin/board/blob/9081bf76bd1aabc1b14ea358ad92d9f19f981414/addon/src/main/java/com/vaadin/board/Board.java#L4)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> import java.util.Collection;
That's the only change in this file. Remove it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/56)*

**Comment by svenruppert** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/56)*

**Comment by svenruppert** [comment]
Reviewed 8 of 18 files at r5.
Review status: 43 of 48 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/56)*

**Comment by svenruppert** [comment]
Reviewed 10 of 18 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/56)*

**Pull request closed without merging**
