### PR TITLE
Fix imageCollage example

### PR DESCRIPTION
**Pull request by rogozinds**
Add javadoc how to use it.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/87)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/examples/ImageCollage.java, line 94 at r1](https://reviewable.io:443/reviews/vaadin/board/87#-KnDuYooC9hCrCK4LLik:-KnDuYooC9hCrCK4LLil:b-vc485z) ([raw file](https://github.com/vaadin/board/blob/b6558dde877d5027bcd3d97df42480d7b54275f9/integration-tests/src/main/java/com/vaadin/addon/board/examples/ImageCollage.java#L94)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>
>     private void createResources() {
>         final String IMAGE_PATH = "image-collage/small/";
>         URL folderResource = ImageCollage.class.getResource(IMAGE_PATH);
>         File folder = new File((folderResource.getFile()));
>         int nImages = folder.list().length;
>         resources = new FileResource[nImages];
>         for (int i = 0; i < nImages; i++) {
>             String fileName = "" + (i+1);
</details>
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>             URL resource = ImageCollage.class.getResource(IMAGE_PATH + fileName + ".jpg");
>             resources[i] = new FileResource(new File(resource.getFile()));
>         }
>     }
</details>


what about avoiding the rename of images with something like:
```
    private void createResources() {
        final String IMAGE_PATH = "image-collage/small/";
        URL folderResource = ImageCollage.class.getResource(IMAGE_PATH);
        File folder = new File((folderResource.getFile()));
        String[] fileNames = folder.list();
        resources = new FileResource[fileNames.length];
        for (int i = 0; i < fileNames.length; i++) {
            URL resource = ImageCollage.class.getResource(IMAGE_PATH + fileNames[i]);
            resources[i] = new FileResource(new File(resource.getFile()));
        }
    }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/87)*

**Comment by rogozinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/examples/ImageCollage.java, line 94 at r1](https://reviewable.io:443/reviews/vaadin/board/87#-KnDuYooC9hCrCK4LLik:-KnDxBzn3gnZJvjIfDF1:b-896fix) ([raw file](https://github.com/vaadin/board/blob/b6558dde877d5027bcd3d97df42480d7b54275f9/integration-tests/src/main/java/com/vaadin/addon/board/examples/ImageCollage.java#L94)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>     private void createResources() {
>         final String IMAGE_PATH = "image-collage/small/";
>         URL folderResource = ImageCollage.class.getResource(IMAGE_PATH);
>         File folder = new File((folderResource.getFile()));
>         int nImages = folder.list().length;
>         resources = new FileResource[nImages];
>         for (int i = 0; i < nImages; i++) {
>             String fileName = "" + (i+1);
>  
>             URL resource = ImageCollage.class.getResource(IMAGE_PATH + fileName + ".jpg");
>             resources[i] = new FileResource(new File(resource.getFile()));
>         }
>     }


what about avoiding the rename of images with something like:
```
    private void createResources() {
        final String IMAGE_PATH = "image-collage/small/";
        URL folderResource = ImageCollage.class.getResource(IMAGE_PATH);
        File folder = new File((folderResource.getFile()));
        String[] fileNames = folder.list();
        resources = new FileResource[fileNames.length];
        for (int i = 0; i < fileNames.length; i++) {
            URL resource = ImageCollage.class.getResource(IMAGE_PATH + fileNames[i]);
            resources[i] = new FileResource(new File(resource.getFile()));
        }
    }
```


</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/87)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/examples/ImageCollage.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/board/87#-KnDzYh7zZOL2Ol1MIdA:-KnDzYh7zZOL2Ol1MIdB:b-ohb9sh) ([raw file](https://github.com/vaadin/board/blob/b6558dde877d5027bcd3d97df42480d7b54275f9/integration-tests/src/main/java/com/vaadin/addon/board/examples/ImageCollage.java#L99)):*
> ```Java
>         container.setStyleName("image-collage-item");
> 
>         n = n % resources.length;
> ```

When calling `createImageBox(1)`, it is actually taking the second image. Should it be `n = (n - 1) % resources.length`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/87)*

**Comment by rogozinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/examples/ImageCollage.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/board/87#-KnDzYh7zZOL2Ol1MIdA:-KnESBgqWuCHUU2f2E4I:b-896fix) ([raw file](https://github.com/vaadin/board/blob/b6558dde877d5027bcd3d97df42480d7b54275f9/integration-tests/src/main/java/com/vaadin/addon/board/examples/ImageCollage.java#L99)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

When calling `createImageBox(1)`, it is actually taking the second image. Should it be `n = (n - 1) % resources.length`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/87)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 19 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/87)*

**Pull request merged**
