### PR TITLE
Fix tests, that they run.

### PR DESCRIPTION
**Pull request by rogozinds**
Remove not nessesary suppliers, lambdas

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/60)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java, line 41 at r2](https://reviewable.io:443/reviews/vaadin/board/60#-KlXparaZvZ-8kAdmPfZ:-KlXparaZvZ-8kAdmPf_:b-djw1wh) ([raw file](https://github.com/vaadin/board/blob/439b6f12b9f21da1a3b49f3c1af816c089a16292/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java#L41)):*
> ```Java
>     public void setup() throws Exception {
>         super.setup();
>         getDriver().manage().window().setSize(new Dimension(1024,768));
> ```

Missing import for `Dimension` class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/60)*

**Comment by rogozinds** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/60)*

**Comment by rogozinds** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java, line 41 at r2](https://reviewable.io:443/reviews/vaadin/board/60#-KlXparaZvZ-8kAdmPfZ:-KlYjypKJENdTpwcnncf:b-896fix) ([raw file](https://github.com/vaadin/board/blob/439b6f12b9f21da1a3b49f3c1af816c089a16292/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java#L41)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Missing import for `Dimension` class
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/60)*

**Comment by rogozinds** [comment]
Reviewed 3 of 6 files at r1, 1 of 1 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/60)*

**Comment by rogozinds** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/60)*

**Comment by rogozinds** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/60)*

**Comment by rogozinds** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java, line 41 at r2](https://reviewable.io:443/reviews/vaadin/board/60#-KlXparaZvZ-8kAdmPfZ:-KlYkbBGmYUpw_9_54X7:b-896fix) ([raw file](https://github.com/vaadin/board/blob/439b6f12b9f21da1a3b49f3c1af816c089a16292/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java#L41)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/60)*

**Pull request merged**
