### PR TITLE
Add docs for using class names, DASH-43

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/6)

### CODE REVIEW

**Comment by Artur-** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 74 at r1](https://reviewable.io:443/reviews/vaadin/board/6#-KdPwJQwVmFekpiaujrh:-KdPwJQwVmFekpiaujri:b-2ubmcm) ([raw file](https://github.com/vaadin/board/blob/e2bd571f56b8ebe36858932dba2b4cca458e1bc0/documentation/webcomponents-api/board-basic-use.asciidoc#L74)):*
> ```AsciiDoc
> [[board.basic-use.styling]]
> 
> == Vaadin Board Styling
> ```

Is there any reason to include "Vaadin Board" in all headers or should it just be "Styling"?

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 76 at r1](https://reviewable.io:443/reviews/vaadin/board/6#-KdPvmDSk2tx58Gmrub_:-KdPvmDSk2tx58Gmruba:bq7z917) ([raw file](https://github.com/vaadin/board/blob/e2bd571f56b8ebe36858932dba2b4cca458e1bc0/documentation/webcomponents-api/board-basic-use.asciidoc#L76)):*
> ```AsciiDoc
> == Vaadin Board Styling
> Vaadin Board rearranges elements in your layout based on available space.
> In some cases you also want to use different styles.
> ```

In some cases you want to use different styles depending on how the elements are laid out, e.g. use smaller font size for mobile devices.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 78 at r1](https://reviewable.io:443/reviews/vaadin/board/6#-KdPveSIOoabmpcrmjlz:-KdPveSIOoabmpcrmjm-:bd33nnb) ([raw file](https://github.com/vaadin/board/blob/e2bd571f56b8ebe36858932dba2b4cca458e1bc0/documentation/webcomponents-api/board-basic-use.asciidoc#L78)):*
> ```AsciiDoc
> In some cases you also want to use different styles.
> For example, use smaller font size for mobile devices.
> Vaadin Board has three predefined class selectors for [classname]#vaadin-board-row# :
> ```

extra space before ":" ?

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 108 at r1](https://reviewable.io:443/reviews/vaadin/board/6#-KdPw8HJzq3vMhJxSuX0:-KdPw8HJzq3vMhJxSuX1:b-15xvb4) ([raw file](https://github.com/vaadin/board/blob/e2bd571f56b8ebe36858932dba2b4cca458e1bc0/documentation/webcomponents-api/board-basic-use.asciidoc#L108)):*
> ```AsciiDoc
>     font-size:10px;
> }
> ----
> ```

enter at end of file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/6)*

**Comment by rogozinds** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 74 at r1](https://reviewable.io:443/reviews/vaadin/board/6#-KdPwJQwVmFekpiaujrh:-KdQHQuXoPE8LaBX6ZjU:b-896fix) ([raw file](https://github.com/vaadin/board/blob/e2bd571f56b8ebe36858932dba2b4cca458e1bc0/documentation/webcomponents-api/board-basic-use.asciidoc#L74)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Is there any reason to include "Vaadin Board" in all headers or should it just be "Styling"?
</blockquote></details>

Done.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 76 at r1](https://reviewable.io:443/reviews/vaadin/board/6#-KdPvmDSk2tx58Gmrub_:-KdQHbzw6edbPCGdfsTL:b-896fix) ([raw file](https://github.com/vaadin/board/blob/e2bd571f56b8ebe36858932dba2b4cca458e1bc0/documentation/webcomponents-api/board-basic-use.asciidoc#L76)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

In some cases you want to use different styles depending on how the elements are laid out, e.g. use smaller font size for mobile devices.
</blockquote></details>

Done.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 78 at r1](https://reviewable.io:443/reviews/vaadin/board/6#-KdPveSIOoabmpcrmjlz:-KdQHcJFzdJr0qhEv2ob:b-896fix) ([raw file](https://github.com/vaadin/board/blob/e2bd571f56b8ebe36858932dba2b4cca458e1bc0/documentation/webcomponents-api/board-basic-use.asciidoc#L78)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

extra space before ":" ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/6)*

**Comment by rogozinds** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 108 at r1](https://reviewable.io:443/reviews/vaadin/board/6#-KdPw8HJzq3vMhJxSuX0:-KdQHgZne1RykqYlRwoR:b-896fix) ([raw file](https://github.com/vaadin/board/blob/e2bd571f56b8ebe36858932dba2b4cca458e1bc0/documentation/webcomponents-api/board-basic-use.asciidoc#L108)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

enter at end of file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/6)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/6)*

**Comment by alvarezguille** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/6#-:-KdQmSaAJvN3fjxh36zx:bnfp4nl)*

**Pull request merged**
