### PR TITLE
Feature/sru 001

### PR DESCRIPTION
**Pull request by svenruppert**
changed the const, that were used inside json. to be comp. to Selenium const.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/40)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/board/40#-KjbEYtFbsw9cHxmUE1q:-KjbEYtFbsw9cHxmUE1r:bwe1tlf) (no related file):*
just a suggestion related to change in capitalization between `"Internet Explorer"` and `BrowserType.IE`

should we force lowercase when we read it in json file to avoid problems? opinions @rogozinds @svenruppert ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/40)*

**Comment by svenruppert** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/board/40#-KjbEYtFbsw9cHxmUE1q:-KjbIP27mtp0Dtpkt2fD:b-tntpd) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

just a suggestion related to change in capitalization between `"Internet Explorer"` and `BrowserType.IE`

should we force lowercase when we read it in json file to avoid problems? opinions @rogozinds @svenruppert ?
</blockquote></details>

in source code i would use the BrowserType const. in Functions I just adding the lowercase as additional step as long as we have no schema for json

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/40)*

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/board/40#-KjbEYtFbsw9cHxmUE1q:-KjbWbxtj0j8hzVge5pn:b-m9pyxo) (no related file):*
<details><summary><i>Previously, svenruppert (Sven Ruppert) wrote…</i></summary><blockquote>

in source code i would use the BrowserType const. in Functions I just adding the lowercase as additional step as long as we have no schema for json
</blockquote></details>

I agree, that would prevent some surprises

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/40)*

**Comment by rogozinds** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/40)*

**Comment by rogozinds** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/40#-:-Kjc8r7QHw8zYsAwW_Io:bnfp4nl)*

**Comment by alvarezguille** [comment]
@svenruppert In the future if possible please add a descriptive title to the PR.
As we are squashing and merging and the title is most probably going to end up as the commit message so it should be more understandable than "Feature/sru 001". 
Now I changed it when merging fab44b3.

**Pull request merged**
