### PR TITLE
Create Java versions of Board examples

### PR DESCRIPTION
**Pull request by DiegoCardoso**
Examples for:
- Row Types
- Image Collage
- Sales Dashboard

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/68)

### CODE REVIEW

**Comment by rogozinds** [comment]
Reviewed 34 of 35 files at r1.
Review status: 34 of 35 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/src/main/resources/com/vaadin/addon/board/examples/.DS_Store, line 0 at r1](https://reviewable.io:443/reviews/vaadin/board/68#-Kmkl_9TK4jlSude2kNj:-Kmkl_9Ug4E0e05twAHz:b-egn5o9) ([raw file](https://github.com/vaadin/board/blob/538497d227ba1298bb01710bfb025cc87c23674b/integration-tests/src/main/resources/com/vaadin/addon/board/examples/.DS_Store#L0)):*
I guess, this is added by mistake?

---

*[integration-tests/src/main/resources/com/vaadin/addon/board/examples/image-collage/.DS_Store, line 0 at r1](https://reviewable.io:443/reviews/vaadin/board/68#-KmklifpdnFdaJPlguYf:-KmklifpdnFdaJPlguYg:b22quet) ([raw file](https://github.com/vaadin/board/blob/538497d227ba1298bb01710bfb025cc87c23674b/integration-tests/src/main/resources/com/vaadin/addon/board/examples/image-collage/.DS_Store#L0)):*
Remove this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/68)*

**Comment by rogozinds** [comment]
Reviewed 1 of 35 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/68)*

**Comment by DiegoCardoso** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/src/main/resources/com/vaadin/addon/board/examples/.DS_Store, line  at r1](https://reviewable.io:443/reviews/vaadin/board/68#-Kmkl_9TK4jlSude2kNj:-KmkxPxZmZ_QZrqLfLc9:b-896fix) ([raw file](https://github.com/vaadin/board/blob/538497d227ba1298bb01710bfb025cc87c23674b/integration-tests/src/main/resources/com/vaadin/addon/board/examples/.DS_Store#L)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

I guess, this is added by mistake?
</blockquote></details>

Done.

---

*[integration-tests/src/main/resources/com/vaadin/addon/board/examples/image-collage/.DS_Store, line  at r1](https://reviewable.io:443/reviews/vaadin/board/68#-KmklifpdnFdaJPlguYf:-KmkxP16RF_cshjpyA5z:b-896fix) ([raw file](https://github.com/vaadin/board/blob/538497d227ba1298bb01710bfb025cc87c23674b/integration-tests/src/main/resources/com/vaadin/addon/board/examples/image-collage/.DS_Store#L)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Remove this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/68)*

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/68#-:-Kml9nZaGRPQu3LLiFmb:bnfp4nl)*

**Pull request merged**
