### PR TITLE
Fix failing maven builds (fix #108)

### LINKED ISSUE #108: Clean maven build fails: "Unable to find suitable version for webcomponentsjs"
When running a clean build with `mvn clean install` it fails with the following error:
```
ERROR] bower                                     ECONFLICT Unable to find suitable version for webcomponentsjs
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.088 s
[INFO] Finished at: 2017-07-17T11:42:40+03:00
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:yarn (yarn install) on project vaadin-board-precompiled: Failed to run task: 'yarn ' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

To reproduce the issue, manually delete the `precompiled/src/main/frontend/bower_components` folder (if exists). `mvn clean` does not delete it automatically.

### PR DESCRIPTION
**Pull request by vlukashov**
Key changes:
 - add `bower_components` and other front-end build folders into the clean list for `mvn clean` (to avoid the same issue in the future)
 - bump the version of WebComponents polyfills up to 1.0.2 to match with the requirements of vaadin-board 1.0.1

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/109)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[precompiled/src/main/frontend/bower.json, line 16 at r4](https://reviewable.io:443/reviews/vaadin/board/109#-KpJHCSEE9Cyo2E3pDyH:-KpJHCSFC0ONL6RPQCMi:b-wp61qi) ([raw file](https://github.com/vaadin/board/blob/2c08b16ea5c0f24fe00453dfdb975e03169f4680/precompiled/src/main/frontend/bower.json#L16)):*
> "webcomponentsjs": "1.0.2"

should this be `"webcomponentsjs": "^1.0.0"` so that there is no issue with next webcomponentsjs minor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/109)*

**Comment by vlukashov** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[precompiled/src/main/frontend/bower.json, line 16 at r4](https://reviewable.io:443/reviews/vaadin/board/109#-KpJHCSEE9Cyo2E3pDyH:-KpJVlPFGpxYlJSbtLh_:b-7ql1td) ([raw file](https://github.com/vaadin/board/blob/2c08b16ea5c0f24fe00453dfdb975e03169f4680/precompiled/src/main/frontend/bower.json#L16)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> "webcomponentsjs": "1.0.2"

should this be `"webcomponentsjs": "^1.0.0"` so that there is no issue with next webcomponentsjs minor?
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/109)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r4.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/109)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/109)*

**Pull request merged**
