### PR TITLE
Fix typo in board example

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/3)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 19 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-Kcrw1Tf5QUKrqa1-bL9:-Kcrw1Tf5QUKrqa1-bLA:b-7flrwh) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L19)):*
> ```AsciiDoc
> [subs="normal"]
> ----
> [prompt]#$# [command]#bower# install --save vaadin-board#[replaceable]#1.x.x#
> ```

This could be
`bower install --save vaadin-board`
to allow copy pasting

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 31 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-Kcrw4pdhVXmfaLZi44h:-Kcrw4pdhVXmfaLZi44i:bpnihb) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L31)):*
> ```AsciiDoc
> <head>
>   <link rel="import" href="bower_components/vaadin-board/vaadin-board.html">
>   <link rel="import" href="bower_components/vaadin-board/vaadin-board-row.html">
> ```

The `vaadin-board-row.html` import should be in `vaadin-board.html`

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 53 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-KcrwNChLDMAb5iGMTFT:-KcrwNChLDMAb5iGMTFU:b5djgkg) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L53)):*
> ```AsciiDoc
> [source, html]
> ----
> <body>
> ```

I would remove `<body>` and just show the snippet (to make it clear that imports etc still need to be there)

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 54 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-KcrwC9C1wGUwUKm1ZzI:-KcrwC9C1wGUwUKm1ZzJ:b-bjl15y) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L54)):*
> ```AsciiDoc
> ----
> <body>
>     <vaadin-board-row>
> ```

Might be clearer to wrap with a `<vaadin-board>` even if it is not technically needed today

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 59 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-KcrwIpLKLOQR-NQR-Nb:-KcrwIpLKLOQR-NQR-Nc:b7lzzl4) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L59)):*
> ```AsciiDoc
>         <div>top C</div>
>     </vaadin-board-row>
>   </div>
> ```

What div does this close?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/3)*

**Comment by alvarezguille** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 19 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-Kcrw1Tf5QUKrqa1-bL9:-KcvNe-V4E1EbuuK_JhL:b-ew92za) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L19)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This could be
`bower install --save vaadin-board`
to allow copy pasting

</blockquote></details>

let's do the `bower register` first

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/3)*

**Comment by rogozinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 19 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-Kcrw1Tf5QUKrqa1-bL9:-Kcve_Szt_XenlSjSWsG:b-896fix) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L19)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

let's do the `bower register` first
</blockquote></details>

Done.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 31 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-Kcrw4pdhVXmfaLZi44h:-KcvedzlADZKT2sYw7Aj:b-896fix) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L31)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

The `vaadin-board-row.html` import should be in `vaadin-board.html`
</blockquote></details>

Done.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 53 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-KcrwNChLDMAb5iGMTFT:-KcvekF_XHms39n7YHA0:b-896fix) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L53)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

I would remove `<body>` and just show the snippet (to make it clear that imports etc still need to be there)
</blockquote></details>

Done.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 54 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-KcrwC9C1wGUwUKm1ZzI:-Kcveq6Wed3IIxCU1y0A:b-896fix) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L54)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Might be clearer to wrap with a `<vaadin-board>` even if it is not technically needed today
</blockquote></details>

Done.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 59 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-KcrwIpLKLOQR-NQR-Nb:-KcveqPlyStyOXldh8v4:b-886gsx) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L59)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

What div does this close?
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/3)*

**Comment by alvarezguille** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 19 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-Kcrw1Tf5QUKrqa1-bL9:-KcvfKL9NF4BFc3OeJl8:b-u6n55t) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L19)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no no, we should do it, only once, before publishing any docs about `bower install vaadin-board`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/3)*

**Comment by alvarezguille** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 19 at r1](https://reviewable.io:443/reviews/vaadin/board/3#-Kcrw1Tf5QUKrqa1-bL9:-Kcvg8478VGq2UVQY00J:bmgifqh) ([raw file](https://github.com/vaadin/board/blob/f628bcf22a3aab2824f8456d165c1da48c2efe48/documentation/webcomponents-api/board-basic-use.asciidoc#L19)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

no no, we should do it, only once, before publishing any docs about `bower install vaadin-board`
</blockquote></details>

remove the line, it's registered now
now `bower install vaadin-board` works

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/3)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/3)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/3)*

**Pull request merged**
