### PR TITLE
Add RemoveComponent test

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/41)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/board/41#-KjbZsUwt5l_R_W98txN:-KjbZsUwt5l_R_W98txO:b-h187b9) ([raw file](https://github.com/vaadin/board/blob/6042a95e81d3c78c99594fb985f5e135390565de/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java#L22)):*
>         ButtonElement btn2 = $(ButtonElement.class).caption("Button 3").first();

it would be more clear if btn2 is named as the caption (btn3)

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/board/41#-Kjb_-bRIfSGvKgZUqDd:-Kjb_-bSkvDiaojmZFJV:b9ytqku) ([raw file](https://github.com/vaadin/board/blob/6042a95e81d3c78c99594fb985f5e135390565de/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java#L25)):*
> "Btn2 should have Y == 0"

Should have same Y as the board

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/41)*

**Comment by rogozinds** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/board/41#-KjbZsUwt5l_R_W98txN:-Kjbd8uDzGE4_hCDopVf:b-896fix) ([raw file](https://github.com/vaadin/board/blob/6042a95e81d3c78c99594fb985f5e135390565de/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java#L22)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>         ButtonElement btn2 = $(ButtonElement.class).caption("Button 3").first();

it would be more clear if btn2 is named as the caption (btn3)
</blockquote></details>

Done.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/board/41#-Kjb_-bRIfSGvKgZUqDd:-KjbdKXWix9Co8Z1tT0W:b-896fix) ([raw file](https://github.com/vaadin/board/blob/6042a95e81d3c78c99594fb985f5e135390565de/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java#L25)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> "Btn2 should have Y == 0"

Should have same Y as the board
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/41)*

**Comment by svenruppert** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/41)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java, line 24 at r2](https://reviewable.io:443/reviews/vaadin/board/41#-KjcMy0oG21gy0VdM4na:-KjcMy0oG21gy0VdM4nb:b4b8v54) ([raw file](https://github.com/vaadin/board/blob/205c9e534055cc683bdd31876beb658cca59c2dd/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java#L24)):*
>         ButtonElement btn1 = $(ButtonElement.class).caption("Button 1").first();
>         ButtonElement btn3 = $(ButtonElement.class).caption("Button 3").first();

These 2 are unused now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/41)*

**Comment by rogozinds** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java, line 24 at r2](https://reviewable.io:443/reviews/vaadin/board/41#-KjcMy0oG21gy0VdM4na:-Kjfwl5-EUVwN_NWwgNa:b-896fix) ([raw file](https://github.com/vaadin/board/blob/205c9e534055cc683bdd31876beb658cca59c2dd/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AddRemoveRowIT.java#L24)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>         ButtonElement btn1 = $(ButtonElement.class).caption("Button 1").first();
>         ButtonElement btn3 = $(ButtonElement.class).caption("Button 3").first();

These 2 are unused now
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/41)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/41)*

**Pull request merged**
