### PR TITLE
Feature/dash 27 one commit

### PR DESCRIPTION
**Pull request by svenruppert**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/57)

### CODE REVIEW

**Comment by rogozinds** [comment]
Reviewed 25 of 53 files at r2.
Review status: 25 of 50 files reviewed at latest revision, 3 unresolved discussions.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java, line 20 at r2](https://reviewable.io:443/reviews/vaadin/board/57#-KlOdmQYoNZ_sZk3Gzfz:-KlOdmQYoNZ_sZk3Gzg-:b46masv) ([raw file](https://github.com/vaadin/board/blob/75a984202d856d55b0c389e74d02febb902ff891/integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java#L20)):*
>   protected abstract Supplier<Component> nextChartInstance();
NO need to have this , you can just use getChart() when adding to layout.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/board/57#-KlOdvGbeYvtnoZDPGFx:-KlOdvGbeYvtnoZDPGFy:bwjtxto) ([raw file](https://github.com/vaadin/board/blob/75a984202d856d55b0c389e74d02febb902ff891/integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java#L26)):*
> .apply(Stream.of(
As far as I know streams are parallel, so there is no order there.
So if you then want to have different components to add, there order will be random.
I don't know is it a problem right now, but just a potential bug, that hard to catch.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicComponents.java, line 41 at r2](https://reviewable.io:443/reviews/vaadin/board/57#-KlOd3ZSTHjAZNlAej42:-KlOd3ZSTHjAZNlAej43:b-4ngbas) ([raw file](https://github.com/vaadin/board/blob/75a984202d856d55b0c389e74d02febb902ff891/integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicComponents.java#L41)):*
>     protected Supplier<Class<? extends Component>> nextClass() {
>       return () -> Button.class;
>     }
You don't need Supplier here, you can just have a method that returns a Component out of it.
Same for all below.
You can a method that returns a tested component (Layout with all the stuff included) or a collection of components you add to your layout in a parent class.
I think it will be much clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/57)*

**Comment by svenruppert** [comment]
Reviewed 3 of 53 files at r2.
Review status: 25 of 50 files reviewed at latest revision, 3 unresolved discussions.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/board/57#-KlOdvGbeYvtnoZDPGFx:-KlOiUwn1guDgJMmgFav:b-cska7i) ([raw file](https://github.com/vaadin/board/blob/75a984202d856d55b0c389e74d02febb902ff891/integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java#L26)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> .apply(Stream.of(
As far as I know streams are parallel, so there is no order there.
So if you then want to have different components to add, there order will be random.
I don't know is it a problem right now, but just a potential bug, that hard to catch.
</blockquote></details>

No, Streams are not parallel. only if you are switching them. So the order is fixed.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/57)*

**Comment by rogozinds** [comment]
Review status: 25 of 50 files reviewed at latest revision, 3 unresolved discussions.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java, line 20 at r2](https://reviewable.io:443/reviews/vaadin/board/57#-KlOdmQYoNZ_sZk3Gzfz:-KlOkQh3TF4eEBC0X_my:b1twljn) ([raw file](https://github.com/vaadin/board/blob/75a984202d856d55b0c389e74d02febb902ff891/integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java#L20)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>   protected abstract Supplier<Component> nextChartInstance();
NO need to have this , you can just use getChart() when adding to layout.
</blockquote></details>

What about his one can you change that ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/57)*

**Comment by rogozinds** [comment]
Reviewed 24 of 53 files at r2.
Review status: 49 of 50 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/57)*

**Comment by rogozinds** [comment]
Reviewed 1 of 53 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 34 at r2](https://reviewable.io:443/reviews/vaadin/board/57#-KlOkg9ABl_thbpxo8tm:-KlOkg9ABl_thbpxo8tn:b-7wgrxq) ([raw file](https://github.com/vaadin/board/blob/75a984202d856d55b0c389e74d02febb902ff891/addon/src/main/java/com/vaadin/board/Board.java#L34)):*
>    * Creates a new row and adds the given components to the row.
>    * <p>
Nothing is change in this file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/57)*

**Comment by svenruppert** [comment]
Reviewed 1 of 2 files at r3.
Review status: 49 of 50 files reviewed at latest revision, 4 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/board/Board.java, line 34 at r2](https://reviewable.io:443/reviews/vaadin/board/57#-KlOkg9ABl_thbpxo8tm:-KlS5FGm8NYyrAKbznml:b-896fix) ([raw file](https://github.com/vaadin/board/blob/75a984202d856d55b0c389e74d02febb902ff891/addon/src/main/java/com/vaadin/board/Board.java#L34)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>    * Creates a new row and adds the given components to the row.
>    * <p>
Nothing is change in this file
</blockquote></details>

Done.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java, line 20 at r2](https://reviewable.io:443/reviews/vaadin/board/57#-KlOdmQYoNZ_sZk3Gzfz:-KlS5-4eyI4I7fdtEDDh:b-896fix) ([raw file](https://github.com/vaadin/board/blob/75a984202d856d55b0c389e74d02febb902ff891/integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java#L20)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

What about his one can you change that ?
</blockquote></details>

Done.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/board/57#-KlOdvGbeYvtnoZDPGFx:-KlS5WywV9-5WdIwk1tF:b-896fix) ([raw file](https://github.com/vaadin/board/blob/75a984202d856d55b0c389e74d02febb902ff891/integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicChartUI.java#L26)):*
<details><summary><i>Previously, svenruppert (Sven Ruppert) wrote…</i></summary><blockquote>

No, Streams are not parallel. only if you are switching them. So the order is fixed.. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/57)*

**Comment by svenruppert** [comment]
Review status: 49 of 50 files reviewed at latest revision, 3 unresolved discussions.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicComponents.java, line 41 at r2](https://reviewable.io:443/reviews/vaadin/board/57#-KlOd3ZSTHjAZNlAej42:-KlS5cpS-uyvyKlux7oM:b-u0t4cc) ([raw file](https://github.com/vaadin/board/blob/75a984202d856d55b0c389e74d02febb902ff891/integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicComponents.java#L41)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>     protected Supplier<Class<? extends Component>> nextClass() {
>       return () -> Button.class;
>     }
You don't need Supplier here, you can just have a method that returns a Component out of it.
Same for all below.
You can a method that returns a tested component (Layout with all the stuff included) or a collection of components you add to your layout in a parent class.
I think it will be much clearer.
</blockquote></details>

as mentioned, I will remove it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/57)*

**Comment by svenruppert** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/57)*

**Comment by svenruppert** [comment]
Reviewed 3 of 6 files at r1, 3 of 53 files at r2, 1 of 2 files at r4.
Review status: 49 of 50 files reviewed at latest revision, 3 unresolved discussions.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicComponents.java, line 41 at r2](https://reviewable.io:443/reviews/vaadin/board/57#-KlOd3ZSTHjAZNlAej42:-KlS7h6-JJXr_BT1wUkM:b-896fix) ([raw file](https://github.com/vaadin/board/blob/75a984202d856d55b0c389e74d02febb902ff891/integration-tests/src/main/java/com/vaadin/addon/board/testUI/CompatBasicComponents.java#L41)):*
<details><summary><i>Previously, svenruppert (Sven Ruppert) wrote…</i></summary><blockquote>

as mentioned, I will remove it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/57)*

**Comment by svenruppert** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/57)*

**Comment by rogozinds** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/57#-:-KlSjdK3RGGY7W-BhkO8:bnfp4nl)*

**Pull request merged**
