### PR TITLE
Add testbench-api for board, fixes DASH-104

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/65)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/board/65#-Km1X3_dwkYP3H5UuXhk:-Km1X3_dwkYP3H5UuXhl:bcm6u5w) (no related file):*
should it be `vaadin-board-testbench-api` instead of `board-testbench-api`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Comment by rogozinds** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/board/65#-Km1X3_dwkYP3H5UuXhk:-Km1c_VGSLazCXzdHp73:b-1hkcgg) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

should it be `vaadin-board-testbench-api` instead of `board-testbench-api`?
</blockquote></details>

It's according to current naming as, board is not called vaadin-board

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Comment by rogozinds** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/board/65#-Km1X3_dwkYP3H5UuXhk:-Km1dEg5femij_2-lqUf:ba179qh) (no related file):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

It's according to current naming as, board is not called vaadin-board
</blockquote></details>

Fixed, as other patch by artur changes artifact names for board and integeration tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Comment by Artur-** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/board/65#-Km5faKvf6_hdq0tdXqh:-Km5faKvf6_hdq0tdXqi:b3for27) ([raw file](https://github.com/vaadin/board/blob/91ddc76c297a969e3da3b26caab8e48633139de9/testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java#L41)):*
> ```Java
>      * @return TestBenchElement direct children from the row.
>      */
>     public List<WebElement> getDirectChildren(){
> ```

This is unnecessary as `$$` or `findElements` will do the job

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Comment by rogozinds** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/board/65#-Km5faKvf6_hdq0tdXqh:-Km68K3g8TA8zkutiZ6_:b-896fix) ([raw file](https://github.com/vaadin/board/blob/91ddc76c297a969e3da3b26caab8e48633139de9/testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java#L41)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This is unnecessary as `$$` or `findElements` will do the job
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Comment by rogozinds** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/board/65#-Km5faKvf6_hdq0tdXqh:-Km68LZ0etv7-0g2b2fM:b-896fix) ([raw file](https://github.com/vaadin/board/blob/91ddc76c297a969e3da3b26caab8e48633139de9/testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java#L41)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Comment by Artur-** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/board/elements/BoardElement.java, line 38 at r2](https://reviewable.io:443/reviews/vaadin/board/65#-Km6DVXSkd1HoAccB9_F:-Km6DVXSkd1HoAccB9_G:b-odhrcz) ([raw file](https://github.com/vaadin/board/blob/82b2331edc24e0ce7024726e5af152c4d0bf57d0/testbench-api/src/main/java/com/vaadin/board/elements/BoardElement.java#L38)):*
> ```Java
>  */
> @ServerClass("com.vaadin.board.Board")
> public class BoardElement extends AbstractElement {
> ```

Should extend `AbstractComponentElement`

---

*[testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java, line 29 at r2](https://reviewable.io:443/reviews/vaadin/board/65#-Km6DMxXg-LOX96f-BTp:-Km6DMxXg-LOX96f-BTq:bgk3fws) ([raw file](https://github.com/vaadin/board/blob/82b2331edc24e0ce7024726e5af152c4d0bf57d0/testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java#L29)):*
> ```Java
>  */
> @ServerClass("com.vaadin.board.Row")
> public class RowElement extends AbstractElement {
> ```

Should extend `AbstractComponentContainerElement`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Comment by rogozinds** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java, line 29 at r2](https://reviewable.io:443/reviews/vaadin/board/65#-Km6DMxXg-LOX96f-BTp:-KmAxGNTBiQTNk_Uu2Q6:b-896fix) ([raw file](https://github.com/vaadin/board/blob/82b2331edc24e0ce7024726e5af152c4d0bf57d0/testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java#L29)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Should extend `AbstractComponentContainerElement`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Comment by Artur-** [comment]
Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---

*[testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java, line 29 at r2](https://reviewable.io:443/reviews/vaadin/board/65#-Km6DMxXg-LOX96f-BTp:-KmAxXGtoQrYVRR7aZPj:bsh4uco) ([raw file](https://github.com/vaadin/board/blob/82b2331edc24e0ce7024726e5af152c4d0bf57d0/testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java#L29)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`Container` still missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Comment by rogozinds** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java, line 29 at r2](https://reviewable.io:443/reviews/vaadin/board/65#-Km6DMxXg-LOX96f-BTp:-KmB0WhSGnk_m9YTjju9:b1cse9w) ([raw file](https://github.com/vaadin/board/blob/82b2331edc24e0ce7024726e5af152c4d0bf57d0/testbench-api/src/main/java/com/vaadin/board/elements/RowElement.java#L29)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

`Container` still missing
</blockquote></details>

Now it's there :), sorry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Comment by alvarezguille** [comment]
Reviewed 8 of 12 files at r1, 2 of 3 files at r2, 2 of 3 files at r3.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/InnerRowIT.java, line 31 at r3](https://reviewable.io:443/reviews/vaadin/board/65#-KmC8vH4NdPxLof9euTf:-KmC8vH4NdPxLof9euTg:btff7pi) ([raw file](https://github.com/vaadin/board/blob/14ed5f56536ca5fd395ce52a798309df73f6e886/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/InnerRowIT.java#L31)):*
>         List<WebElement> innerRow = board.findElements(By.xpath("//vaadin-board/vaadin-board-row/vaadin-board-row"));
>         List<WebElement> innerRowChildren = board.findElements(By.xpath("//vaadin-board/vaadin-board-row/vaadin-board-row/*"));

it could use element query, but we can change it later too

---

*[testbench-api/pom.xml, line 41 at r3](https://reviewable.io:443/reviews/vaadin/board/65#-KmC9LatL8XyHTBd_B6k:-KmC9LaurLDMknmcSvdL:b1ub6qs) ([raw file](https://github.com/vaadin/board/blob/14ed5f56536ca5fd395ce52a798309df73f6e886/testbench-api/pom.xml#L41)):*
> <failOnError>false</failOnError>

this might result in javadoc jar not deployed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/65)*

**Pull request merged**
