### PR TITLE
Add docs for Java-API chapter, fixes DASH-30

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/44)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Looks good in general, I'll check in detail and run the getting started steps later

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/java-api/board-basic-use.asciidoc, line 40 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjmVulwI9HlfFAbzPJf:-KjmVulwI9HlfFAbzPJg:b4rijbx) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/board-basic-use.asciidoc#L40)):*
>  ot 

to

---

*[documentation/java-api/board-installing.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjmXW5ucqtPzmy1_oN7:-KjmXW5ucqtPzmy1_oN8:b28qxcr) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/board-installing.asciidoc#L15)):*
> 1.0.0

I'm not so sure about using the final version here since docs will be published before when only alphas or beta are available

---

*[documentation/java-api/board-installing.asciidoc, line 51 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjmWhSYmoWQl7-O_ZwM:-KjmWhSYmoWQl7-O_ZwN:bxdplwl) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/board-installing.asciidoc#L51)):*
> You can purchase Vaadin Board

Purchase is not an option for board I think, let's confirm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/44#-:-KjmXvL5UmS241Ty06y4:bqk53ps)*

**Comment by alvarezguille** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[documentation/java-api/board-basic-use.asciidoc, line 12 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqQpIUvWONG8jEZCZ0:-KjqQpIUvWONG8jEZCZ1:b-3ussy8) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/board-basic-use.asciidoc#L12)):*
> <<./getting-started#board.introduction,"Getting Started Section">>

This should link to the installing chapter

---

*[documentation/java-api/board-basic-use.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqQwDHuFTpO8gY6ifA:-KjqQwDHuFTpO8gY6ifB:bdd9nh0) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/board-basic-use.asciidoc#L17)):*
> [classname]#Row#

Row class

---

*[documentation/java-api/board-basic-use.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqR2K6BRf5DaxOAg-b:-KjqR2K6BRf5DaxOAg-c:bojmruv) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/board-basic-use.asciidoc#L21)):*
> Based on available space, the vaadin board rearranges child elements based on available space.

"Based on available space" is repeated

---

*[documentation/java-api/board-basic-use.asciidoc, line 24 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqRFIHeApwQ-jw_GvX:-KjqRFIHeApwQ-jw_GvY:b64dx7p) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/board-basic-use.asciidoc#L24)):*
> In the example below every child [classname]#Label# will use 33% on Desktop, but will be
> rearranged to two rows when switching to tablet: one row with 2 items 50% of available space each and second row
> with 100% width item, see example below.

is that current behavior in tablet mode? It should be 3 columns in desktop, 3 columns in tablet and 1 column in mobile

---

*[documentation/java-api/board-basic-use.asciidoc, line 39 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqRZdy350FpDr4rbQK:-KjqRZdy350FpDr4rbQL:bjm3pzo) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/board-basic-use.asciidoc#L39)):*
> You can specify the width of the inner element in a [classname]#Row#.

I wouldn't talk of width. This is covered by the following line that refers to columns. I would delete it.

---

*[documentation/java-api/board-basic-use.asciidoc, line 101 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqSWixs5rtq1ObWSJg:-KjqSWiy0j1cBc7CCgE8:b-o8eb0q) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/board-basic-use.asciidoc#L101)):*
> has

labels have

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/44)*

**Comment by alvarezguille** [comment]
Review status: 0 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

*[documentation/java-api/board-installing.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqZuGTk-LquB8MCPKC:-KjqZuGTk-LquB8MCPKD:bzhg3lv) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/board-installing.asciidoc#L15)):*
> 8.0

It's actually 8.1 or later

---

*[documentation/java-api/getting-started.asciidoc, line 32 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqeO85ITlPTHl1viyV:-KjqeO85ITlPTHl1viyW:brisejd) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/getting-started.asciidoc#L32)):*
> #8.0.0#

should be latest alpha of 8.1 and then updated if/when it's released

---

*[documentation/java-api/getting-started.asciidoc, line 90 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-Kjqe8lmvTjW__Vm_ajC:-Kjqe8lmvTjW__Vm_ajD:bh52cg3) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/getting-started.asciidoc#L90)):*
> ```AsciiDoc
> </dependencies>
> ...
> ----
> ```

Instructions to add frontend plugin should be added

---

*[documentation/java-api/getting-started.asciidoc, line 161 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqeGLVCOgkCm3KeKwW:-KjqeGLW5LJKmfGzNVfU:b-efk17j) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/getting-started.asciidoc#L161)):*
> [command]#mvn# jetty:run

`jetty:run` is not enough

`package jetty:run` should be

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/44)*

**Comment by Artur-** [comment]
Review status: 0 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

*[documentation/java-api/getting-started.asciidoc, line 161 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqeGLVCOgkCm3KeKwW:-Kjqeld4UrCcAgWuzVGH:b-pf7t0m) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/getting-started.asciidoc#L161)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> [command]#mvn# jetty:run

`jetty:run` is not enough

`package jetty:run` should be
</blockquote></details>

Why is `jetty:run` not enough?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/44)*

**Comment by alvarezguille** [comment]
*[documentation/java-api/getting-started.asciidoc, line 161 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqeGLVCOgkCm3KeKwW:-Kjran5knZt44nGeHZuC:b-xr051p) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/getting-started.asciidoc#L161)):*
> jetty:run is not enough
> package jetty:run should be

that's the answer I got when it didn't work, if it's enough just leave it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/44)*

**Comment by Artur-** [comment]
Review status: 0 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

*[documentation/java-api/getting-started.asciidoc, line 161 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqeGLVCOgkCm3KeKwW:-Kjrcp5s9v1oSa28-ru0:baifc8) ([raw file](https://github.com/vaadin/board/blob/e27e47ea538875f527227a03ee7a2640cb3d4546/documentation/java-api/getting-started.asciidoc#L161)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> jetty:run is not enough
> package jetty:run should be

that's the answer I got when it didn't work, if it's enough just leave it
</blockquote></details>

`jetty:run` *should* run package and everything needed. Better test that the instructions actually work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/44)*

**Comment by rogozinds** [comment]
Review status: 0 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

*[documentation/java-api/board-basic-use.asciidoc, line 12 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqQpIUvWONG8jEZCZ0:-KjwRCbqhFqRRh30JjMQ:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-basic-use.asciidoc#L12)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> <<./getting-started#board.introduction,"Getting Started Section">>

This should link to the installing chapter
</blockquote></details>

Done.

---

*[documentation/java-api/board-basic-use.asciidoc, line 24 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqRFIHeApwQ-jw_GvX:-KjwSDM4I_-QRKcWI3r3:brdo44y) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-basic-use.asciidoc#L24)):*
>  
> [source, java]
> ----
>         setContent(board);
> ----
>  
> You can specify the width of the inner element in a [classname]#Row#.
Changed example to have 4 labels, to show the difference between tablet and desktop.

---

*[documentation/java-api/board-basic-use.asciidoc, line 101 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqSWixs5rtq1ObWSJg:-KjwScNSeRH3o_mPd9aQ:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-basic-use.asciidoc#L101)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> has

labels have
</blockquote></details>

Done.

---

*[documentation/java-api/board-installing.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqZuGTk-LquB8MCPKC:-KjwT-bTFWTsUKnaDOy8:b-7wequf) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-installing.asciidoc#L15)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> 8.0

It's actually 8.1 or later
</blockquote></details>

I've Changed to 8.1.0-beta1. Apparently we won't publish docs before. Then we can change to 8.1.0

---

*[documentation/java-api/getting-started.asciidoc, line 90 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-Kjqe8lmvTjW__Vm_ajC:-KjwVZXzFJVhsX--mqF4:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/getting-started.asciidoc#L90)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

Instructions to add frontend plugin should be added
</blockquote></details>

Done.

---

*[documentation/java-api/getting-started.asciidoc, line 161 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqeGLVCOgkCm3KeKwW:-KjwYuz-qCgdbnpUlsAo:bvjvc59) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/getting-started.asciidoc#L161)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

`jetty:run` *should* run package and everything needed. Better test that the instructions actually work
</blockquote></details>

I've checked just calling jetty is enough.
According to docs
"Instead, Jetty deploys the webapp from its sources." So 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/44)*

**Comment by rogozinds** [comment]
Review status: 0 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

*[documentation/java-api/board-basic-use.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqQwDHuFTpO8gY6ifA:-KjwZIqMe6rk38Oy6MLT:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-basic-use.asciidoc#L17)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> [classname]#Row#

Row class
</blockquote></details>

Done.

---

*[documentation/java-api/board-basic-use.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqR2K6BRf5DaxOAg-b:-KjwZJbZBjeRnyopkX7n:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-basic-use.asciidoc#L21)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> Based on available space, the vaadin board rearranges child elements based on available space.

"Based on available space" is repeated
</blockquote></details>

Done.

---

*[documentation/java-api/board-basic-use.asciidoc, line 24 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqRFIHeApwQ-jw_GvX:-KjwZMgqzGffOrtGbmA-:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-basic-use.asciidoc#L24)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>  
> [source, java]
> ----
>         setContent(board);
> ----
>  
> You can specify the width of the inner element in a [classname]#Row#.
Changed example to have 4 labels, to show the difference between tablet and desktop.
</blockquote></details>

Done.

---

*[documentation/java-api/board-basic-use.asciidoc, line 39 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqRZdy350FpDr4rbQK:-KjwZVy6M8hbBwvX_uaU:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-basic-use.asciidoc#L39)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> You can specify the width of the inner element in a [classname]#Row#.

I wouldn't talk of width. This is covered by the following line that refers to columns. I would delete it.
</blockquote></details>

Done.

---

*[documentation/java-api/board-basic-use.asciidoc, line 40 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjmVulwI9HlfFAbzPJf:-KjwZVAChXvXDGetjThg:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-basic-use.asciidoc#L40)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>  ot 

to
</blockquote></details>

Done.

---

*[documentation/java-api/board-basic-use.asciidoc, line 101 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqSWixs5rtq1ObWSJg:-KjwZWcRz4IlhZ7Jr3JC:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-basic-use.asciidoc#L101)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[documentation/java-api/board-installing.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjmXW5ucqtPzmy1_oN7:-KjwZXN6SDpfkF1_4cb5:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-installing.asciidoc#L15)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> 1.0.0

I'm not so sure about using the final version here since docs will be published before when only alphas or beta are available
</blockquote></details>

Done.

---

*[documentation/java-api/board-installing.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqZuGTk-LquB8MCPKC:-KjwZXs_0aWo0myfyDfV:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-installing.asciidoc#L15)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

I've Changed to 8.1.0-beta1. Apparently we won't publish docs before. Then we can change to 8.1.0
</blockquote></details>

Done.

---

*[documentation/java-api/board-installing.asciidoc, line 51 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjmWhSYmoWQl7-O_ZwM:-KjwZYt4OhMZIy1Qc90e:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/board-installing.asciidoc#L51)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> You can purchase Vaadin Board

Purchase is not an option for board I think, let's confirm
</blockquote></details>

Done.

---

*[documentation/java-api/getting-started.asciidoc, line 32 at r1](https://reviewable.io:443/reviews/vaadin/board/44#-KjqeO85ITlPTHl1viyV:-KjwZZwn008tBZhytlC8:b-896fix) ([raw file](https://github.com/vaadin/board/blob/1e92977bf0225ae045e7e903836990bca8f0c9f8/documentation/java-api/getting-started.asciidoc#L32)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> #8.0.0#

should be latest alpha of 8.1 and then updated if/when it's released
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/44)*

**Comment by alvarezguille** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/java-api/basic-use.asciidoc, line 24 at r2](https://reviewable.io:443/reviews/vaadin/board/44#-KkB7CPrATpI_yEObiCu:-KkB7CPrATpI_yEObiCv:b-s82snp) ([raw file](https://github.com/vaadin/board/blob/ff7904d42782e732546a6b1a386668fb2a23dcf7/documentation/java-api/basic-use.asciidoc#L24)):*
> one row with 2 items 50% of available space each and second row
> with 100% width item, see example below.

both with 2 items with 50% width

---

*[documentation/java-api/getting-started.asciidoc, line 94 at r2](https://reviewable.io:443/reviews/vaadin/board/44#-KkB7ZyuumXeXlB8w6Cg:-KkB7ZyuumXeXlB8w6Ch:b-625tqj) ([raw file](https://github.com/vaadin/board/blob/ff7904d42782e732546a6b1a386668fb2a23dcf7/documentation/java-api/getting-started.asciidoc#L94)):*
> to you POM.xml

typo: your

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/44)*

**Comment by rogozinds** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/java-api/basic-use.asciidoc, line 24 at r2](https://reviewable.io:443/reviews/vaadin/board/44#-KkB7CPrATpI_yEObiCu:-KkBGWxACyfSDFzn28rn:b-896fix) ([raw file](https://github.com/vaadin/board/blob/ff7904d42782e732546a6b1a386668fb2a23dcf7/documentation/java-api/basic-use.asciidoc#L24)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> one row with 2 items 50% of available space each and second row
> with 100% width item, see example below.

both with 2 items with 50% width
</blockquote></details>

Done.

---

*[documentation/java-api/getting-started.asciidoc, line 94 at r2](https://reviewable.io:443/reviews/vaadin/board/44#-KkB7ZyuumXeXlB8w6Cg:-KkBGdwo4qFxgdFg0XoC:b-896fix) ([raw file](https://github.com/vaadin/board/blob/ff7904d42782e732546a6b1a386668fb2a23dcf7/documentation/java-api/getting-started.asciidoc#L94)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> to you POM.xml

typo: your
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/44)*

**Comment by alvarezguille** [comment]
Reviewed 3 of 8 files at r1, 3 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/44)*

**Pull request merged**
