### PR TITLE
Mention redraw() in basic use docs

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/4)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 75 at r1](https://reviewable.io:443/reviews/vaadin/board/4#-Kd6IO_d4krFCV1j0DI-:-Kd6IO_d4krFCV1j0DI0:b-gxgqnf) ([raw file](https://github.com/vaadin/board/blob/23acdf19798dc4b97fd0bffe44173086370bad68/documentation/webcomponents-api/board-basic-use.asciidoc#L75)):*
> ```AsciiDoc
> === Redraw method
> 
> Vaadin Board relies on window resize events to achieve responsiveness.
> ```

Doesn't it rely on IronResize events?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/4)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/4)*

**Comment by rogozinds** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 75 at r1](https://reviewable.io:443/reviews/vaadin/board/4#-Kd6IO_d4krFCV1j0DI-:-Kd6QDkwA_j_s3yEIamy:b-jeslk) ([raw file](https://github.com/vaadin/board/blob/23acdf19798dc4b97fd0bffe44173086370bad68/documentation/webcomponents-api/board-basic-use.asciidoc#L75)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Doesn't it rely on IronResize events?
</blockquote></details>

That's true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/4)*

**Comment by rogozinds** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/4)*

**Comment by alvarezguille** [comment]
*[documentation/webcomponents-api/board-basic-use.asciidoc, line 75 at r1](https://reviewable.io:443/reviews/vaadin/board/4#-Kd6IO_d4krFCV1j0DI-:-Ke3LMwwQe254vtpnyl7:bwc304o) ([raw file](https://github.com/vaadin/board/blob/23acdf19798dc4b97fd0bffe44173086370bad68/documentation/webcomponents-api/board-basic-use.asciidoc#L75)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

That's true.
</blockquote></details>

sounds like implementation details, right now we have our own version of ironresize, do we want to go into that detail for docs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/4)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/webcomponents-api/board-basic-use.asciidoc, line 75 at r1](https://reviewable.io:443/reviews/vaadin/board/4#-Kd6IO_d4krFCV1j0DI-:-Ke3Mbg6h-Kn0a68jtbW:bwlvblj) ([raw file](https://github.com/vaadin/board/blob/23acdf19798dc4b97fd0bffe44173086370bad68/documentation/webcomponents-api/board-basic-use.asciidoc#L75)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

sounds like implementation details, right now we have our own version of ironresize, do we want to go into that detail for docs?
</blockquote></details>

Remove "window", then it is true

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/4)*

**Comment by alvarezguille** [comment]
*[documentation/webcomponents-api/board-basic-use.asciidoc, line 75 at r1](https://reviewable.io:443/reviews/vaadin/board/4#-Kd6IO_d4krFCV1j0DI-:-Ke3NZUhYwxabSys_tj6:bngllrr) ([raw file](https://github.com/vaadin/board/blob/23acdf19798dc4b97fd0bffe44173086370bad68/documentation/webcomponents-api/board-basic-use.asciidoc#L75)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Remove "window", then it is true
</blockquote></details>

sounds good, done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/4)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/4)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/4)*

**Pull request merged**
