### PR TITLE
Add tip to docs to use body unresolved

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/12)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[documentation/board-overview.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/board/12#-Kebq_JuEld_HrCct6aa:-Kebq_JvzoEUSHXD2UYB:b-fif8qf) ([raw file](https://github.com/vaadin/board/blob/f1f668b2533a2e60feb5f9db6c7c4be91732bdd8/documentation/board-overview.asciidoc#L22)):*
> ```AsciiDoc
> 
> - Because non-chrome browsers need to load a polyfill, you can see flickering, before definition of the web component comes in.
>   You can suspend rendering the component before it is ready by adding the "unresolved" tag in body:
> ```

extra space at beginning.
use markup for unresolved
unresolved is not a tag

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/12)*

**Comment by rogozinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[documentation/board-overview.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/board/12#-Kebq_JuEld_HrCct6aa:-KebtoXQ0xaHoxpiTzfa:b-896fix) ([raw file](https://github.com/vaadin/board/blob/f1f668b2533a2e60feb5f9db6c7c4be91732bdd8/documentation/board-overview.asciidoc#L22)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

extra space at beginning.
use markup for unresolved
unresolved is not a tag
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/12)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/12)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[documentation/board-overview.asciidoc, line 9 at r2](https://reviewable.io:443/reviews/vaadin/board/12#-KeclUXBIzyntwqP6jD6:-KeclUXBIzyntwqP6jD7:b-f5q612) ([raw file](https://github.com/vaadin/board/blob/bb8270cc1bc8d39089e3bb8a08685089853342a9/documentation/board-overview.asciidoc#L9)):*
> = Overview
> The [elementname]#vaadin-board# is a Polymer element for creating flexible responsive layouts

Can you add an empty line between header and content?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/12)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/12)*

**Pull request merged**
