### PR TITLE
Initial Tests setup

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/board/36)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/board/36#-KjMPvu_1iU3TjfwKgnt:-KjMPvu_1iU3TjfwKgnu:b-3ret1v) (no related file):*
isn't maven-failsafe-plugin config missing?
should the the test classes end in IT.java or any of the default include pattern?

---

*[integration-tests/src/main/java/com/vaadin/addon/board/TestServlet.java, line 9 at r2](https://reviewable.io:443/reviews/vaadin/board/36#-KjMOUUdY4HTqtRoB-AU:-KjMOUUdY4HTqtRoB-AV:bwcnspv) ([raw file](https://github.com/vaadin/board/blob/126c461cb086288fc47e48fba0ba90a352014dcc/integration-tests/src/main/java/com/vaadin/addon/board/TestServlet.java#L9)):*
> //@WebServlet(urlPatterns = "/*", name = "TestServlet", asyncSupported = true, initParams = {
> //    @WebInitParam(name = "UIProvider", value = "com.vaadin.addon.board.testUI.TestUIProvider")
> //})
> //@VaadinServletConfiguration(ui = ExampleUI.class, productionMode = false, widgetset ="com.vaadin.addon.board.AppWidgetSet")


remove commented code

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/BasicUI.java, line 9 at r2](https://reviewable.io:443/reviews/vaadin/board/36#-KjMOpJL3MpRBp_mMGkP:-KjMOpJL3MpRBp_mMGkQ:b-q5ilnb) ([raw file](https://github.com/vaadin/board/blob/126c461cb086288fc47e48fba0ba90a352014dcc/integration-tests/src/main/java/com/vaadin/addon/board/testUI/BasicUI.java#L9)):*
> @Theme("mytheme")

can this be set up for all tests UIs at once?

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java, line 128 at r2](https://reviewable.io:443/reviews/vaadin/board/36#-KjMP90jL0oK1m2sgT5x:-KjMP90jL0oK1m2sgT5y:b-g2r1gy) ([raw file](https://github.com/vaadin/board/blob/126c461cb086288fc47e48fba0ba90a352014dcc/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java#L128)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>
>     //TODO this should be removed when component itself removes the license checker.
>     private void  removeLicenseChecker(){
>         WebDriver driver = getDriver();
>         JavascriptExecutor js;
>         if (driver instanceof JavascriptExecutor) {
>             js = (JavascriptExecutor) driver;
>             js.executeScript("var elem = document.querySelector(\"vaadin-license-dialog\");"
>                 + "if(elem) {elem.style=\"display:none\";}");
>         }
</details>
>  
>     }

can you mention this in DASH-46 so it's not forgotten?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/36)*

**Comment by rogozinds** [comment]
Review status: 0 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/TestServlet.java, line 9 at r2](https://reviewable.io:443/reviews/vaadin/board/36#-KjMOUUdY4HTqtRoB-AU:-KjMS8TNTcozSQNi2TKh:b-896fix) ([raw file](https://github.com/vaadin/board/blob/126c461cb086288fc47e48fba0ba90a352014dcc/integration-tests/src/main/java/com/vaadin/addon/board/TestServlet.java#L9)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> //@WebServlet(urlPatterns = "/*", name = "TestServlet", asyncSupported = true, initParams = {
> //    @WebInitParam(name = "UIProvider", value = "com.vaadin.addon.board.testUI.TestUIProvider")
> //})
> //@VaadinServletConfiguration(ui = ExampleUI.class, productionMode = false, widgetset ="com.vaadin.addon.board.AppWidgetSet")


remove commented code
</blockquote></details>

Done.

---

*[integration-tests/src/main/java/com/vaadin/addon/board/testUI/BasicUI.java, line 9 at r2](https://reviewable.io:443/reviews/vaadin/board/36#-KjMOpJL3MpRBp_mMGkP:-KjMTHVP3f_tsXwelFmB:b-896fix) ([raw file](https://github.com/vaadin/board/blob/126c461cb086288fc47e48fba0ba90a352014dcc/integration-tests/src/main/java/com/vaadin/addon/board/testUI/BasicUI.java#L9)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> @Theme("mytheme")

can this be set up for all tests UIs at once?
</blockquote></details>

Done.

---

*[integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java, line 128 at r2](https://reviewable.io:443/reviews/vaadin/board/36#-KjMP90jL0oK1m2sgT5x:-KjMTKkU-N148n-aZuTz:b-896fix) ([raw file](https://github.com/vaadin/board/blob/126c461cb086288fc47e48fba0ba90a352014dcc/integration-tests/src/test/java/com/vaadin/addon/board/testbenchtests/AbstractParallelTest.java#L128)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>     //TODO this should be removed when component itself removes the license checker.
>     private void  removeLicenseChecker(){
>         WebDriver driver = getDriver();
>         JavascriptExecutor js;
>         if (driver instanceof JavascriptExecutor) {
>             js = (JavascriptExecutor) driver;
>             js.executeScript("var elem = document.querySelector(\"vaadin-license-dialog\");"
>                 + "if(elem) {elem.style=\"display:none\";}");
>         }
>  
>     }

can you mention this in DASH-46 so it's not forgotten?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/36)*

**Comment by alvarezguille** [comment]
Reviewed 9 of 21 files at r2, 15 of 15 files at r3.
Review status: 20 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/36)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/board/36)*

**Pull request merged**
